/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.scouthq.view;

import edu.ijse.scouthq.controller.ControllerFactory;
import edu.ijse.scouthq.controller.custom.TeacherController;
import edu.ijse.scouthq.dto.MeritBadgeTeacherDTO;
import edu.ijse.scouthq.dto.TeacherDTO;
import static edu.ijse.scouthq.view.DiningArea.viewWhatPane;
import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Reshan Pubudu
 */
public class AddMeritBadge extends javax.swing.JPanel {

    /**
     * Creates new form addBadge
     */
    TeacherController ctrlTeacher;
    
    
    public AddMeritBadge() {
        initComponents();
        
        ctrlTeacher = (TeacherController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.TEACHER);
        //teacherTbl.setBackground(Color.white);
        setTeacherId();
        //teacherTbl.removeAll();
        categoryId = "BSC01";
        headLbl.setText("New Scout Merit Badges");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        discriptionLbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        teacherCmb = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        teacherTbl = new javax.swing.JTable();
        badgeNameLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTxtAry = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        badgeIdTxtFld = new javax.swing.JTextField();
        badgeNameTxtFld = new javax.swing.JTextField();
        techersLbl = new javax.swing.JLabel();
        badgeIdLbl = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        scoutMrtLbl = new javax.swing.JLabel();
        roverMrtLbl = new javax.swing.JLabel();
        roverLbl = new javax.swing.JLabel();
        cubScoutMrtLbl = new javax.swing.JLabel();
        headLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setOpaque(false);
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        jPanel1.setOpaque(false);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText(":");

        discriptionLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        discriptionLbl.setText("Description");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        teacherCmb.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        teacherCmb.setToolTipText("Select Qualified Teachers");
        teacherCmb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        teacherCmb.setOpaque(false);
        teacherCmb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacherCmbMouseClicked(evt);
            }
        });
        teacherCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherCmbActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText(":");

        jScrollPane4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane4MouseClicked(evt);
            }
        });

        teacherTbl.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        teacherTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", ""
            }
        ));
        teacherTbl.setToolTipText("If you want to remove Qualified Teacher, then select row..");
        teacherTbl.setColumnSelectionAllowed(true);
        teacherTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacherTblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                teacherTblMouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(teacherTbl);
        teacherTbl.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (teacherTbl.getColumnModel().getColumnCount() > 0) {
            teacherTbl.getColumnModel().getColumn(0).setPreferredWidth(100);
            teacherTbl.getColumnModel().getColumn(1).setPreferredWidth(400);
        }

        badgeNameLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        badgeNameLbl.setText("Badge Name");

        descriptionTxtAry.setColumns(20);
        descriptionTxtAry.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        descriptionTxtAry.setRows(5);
        descriptionTxtAry.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 240, 240), 1, true));
        descriptionTxtAry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descriptionTxtAryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(descriptionTxtAry);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText(":");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Finish");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        badgeIdTxtFld.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        badgeIdTxtFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        badgeIdTxtFld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                badgeIdTxtFldMouseClicked(evt);
            }
        });
        badgeIdTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                badgeIdTxtFldActionPerformed(evt);
            }
        });

        badgeNameTxtFld.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        badgeNameTxtFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        badgeNameTxtFld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                badgeNameTxtFldMouseClicked(evt);
            }
        });
        badgeNameTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                badgeNameTxtFldActionPerformed(evt);
            }
        });

        techersLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        techersLbl.setText("Qualified Teachers");

        badgeIdLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        badgeIdLbl.setText("Badge Id");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText(":");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(badgeNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(badgeNameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(badgeIdLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(badgeIdTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(techersLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(teacherCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(847, 847, 847)
                        .addComponent(jButton1)
                        .addGap(10, 10, 10)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(discriptionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(badgeNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(badgeNameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(badgeIdLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(badgeIdTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(techersLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(teacherCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(discriptionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jScrollPane4.getViewport().setBackground(Color.WHITE);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setOpaque(false);

        scoutMrtLbl.setBackground(new java.awt.Color(170, 204, 255));
        scoutMrtLbl.setDisplayedMnemonic('b');
        scoutMrtLbl.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        scoutMrtLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoutMrtLbl.setText("Scout Merit Badge");
        scoutMrtLbl.setToolTipText("New Boy/Girl Scouts merit badges add");
        scoutMrtLbl.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        scoutMrtLbl.setName("catagory"); // NOI18N
        scoutMrtLbl.setOpaque(true);
        scoutMrtLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scoutMrtLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                scoutMrtLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                scoutMrtLblMouseExited(evt);
            }
        });

        roverMrtLbl.setBackground(new java.awt.Color(170, 204, 255));
        roverMrtLbl.setDisplayedMnemonic('g');
        roverMrtLbl.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        roverMrtLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roverMrtLbl.setText("Rover Merit Badge");
        roverMrtLbl.setToolTipText("New Rover scout merit badges add");
        roverMrtLbl.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        roverMrtLbl.setName("catagory"); // NOI18N
        roverMrtLbl.setOpaque(true);
        roverMrtLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roverMrtLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                roverMrtLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                roverMrtLblMouseExited(evt);
            }
        });

        roverLbl.setBackground(new java.awt.Color(170, 204, 255));
        roverLbl.setDisplayedMnemonic('r');
        roverLbl.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        roverLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roverLbl.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        roverLbl.setName("catagory"); // NOI18N
        roverLbl.setOpaque(true);
        roverLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roverLblMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                roverLblMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                roverLblMouseReleased(evt);
            }
        });

        cubScoutMrtLbl.setBackground(new java.awt.Color(170, 204, 255));
        cubScoutMrtLbl.setDisplayedMnemonic('c');
        cubScoutMrtLbl.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        cubScoutMrtLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cubScoutMrtLbl.setText(" Cub Scout Merit Badge");
        cubScoutMrtLbl.setToolTipText("New Cub Scouts metit badges add");
        cubScoutMrtLbl.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        cubScoutMrtLbl.setName("catagory"); // NOI18N
        cubScoutMrtLbl.setOpaque(true);
        cubScoutMrtLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cubScoutMrtLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cubScoutMrtLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cubScoutMrtLblMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(cubScoutMrtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(scoutMrtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(roverMrtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(roverLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cubScoutMrtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(scoutMrtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(roverMrtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(roverLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        headLbl.setBackground(new java.awt.Color(0, 0, 204));
        headLbl.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        headLbl.setForeground(new java.awt.Color(0, 0, 255));
        headLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headLbl.setText(" ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(headLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(headLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/scouthq/image/winter-stripes-background11.jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(1140, 862));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void scoutMrtLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scoutMrtLblMouseClicked
        headLbl.setText("New Scout Merit Badges");
        
        viewWhatPane.setVisible(false);
        categoryId = "BSC01";
    }//GEN-LAST:event_scoutMrtLblMouseClicked

    private void roverMrtLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roverMrtLblMouseClicked
        headLbl.setText("New Rover Scout Merit Badges");
        
        viewWhatPane.setVisible(false);
        categoryId = "RSC01";
    }//GEN-LAST:event_roverMrtLblMouseClicked

    private void roverLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roverLblMouseClicked
        /*roverLbl.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        roverLbl.setBackground(new Color(255, 255, 255));
        girlScoutLbl.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        girlScoutLbl.setBackground(new Color(240, 240, 240));
        scoutLbl.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        scoutLbl.setBackground(new Color(240, 240, 240));
        cubScoutLbl.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        cubScoutLbl.setBackground(new Color(240, 240, 240));
        */
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_roverLblMouseClicked

    private void roverLblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roverLblMousePressed
        
    }//GEN-LAST:event_roverLblMousePressed

    private void roverLblMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roverLblMouseReleased
        
    }//GEN-LAST:event_roverLblMouseReleased

    private void cubScoutMrtLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cubScoutMrtLblMouseClicked
        headLbl.setText("New Cub Scout Merit Badges");
        
        viewWhatPane.setVisible(false);
        categoryId = "CSC01";
    }//GEN-LAST:event_cubScoutMrtLblMouseClicked

    private void badgeNameTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_badgeNameTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_badgeNameTxtFldActionPerformed

    private void badgeIdTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_badgeIdTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_badgeIdTxtFldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        badgeIdTxtFld.setText("");
        badgeNameTxtFld.setText("");
        descriptionTxtAry.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String badgeId = badgeIdTxtFld.getText();
        String badgeName = badgeNameTxtFld.getText();
        String description = descriptionTxtAry.getText();
        
        DefaultTableModel dtm = (DefaultTableModel)teacherTbl.getModel();
        ArrayList <MeritBadgeTeacherDTO> meritBadgeTeacherDTO = new ArrayList<>();
        for(int i = 0; i< dtm.getRowCount(); i++){
            String id = (String) dtm.getValueAt(i, 0);
            MeritBadgeTeacherDTO meritTeacher = new MeritBadgeTeacherDTO(badgeId, id);
            meritBadgeTeacherDTO.add(meritTeacher);
        }
        
        ConformationForm.badgeId = badgeId;
        ConformationForm.categoryId = categoryId;
        ConformationForm.badgeName = badgeName;
        ConformationForm.badgeDescription = description;
        ConformationForm.meritBadgeTeacherDTO = meritBadgeTeacherDTO;
        
        /*String tId = description;
        String[] id = tId.split(" ");
        for(String i : id){
            if(!i.equals("")||i.equals(" ")){
                System.out.println(i);
            }
        }*/
        
        ConformationForm.sc = "Merit Badge";
        new ConformationForm().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void teacherCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherCmbActionPerformed
        try {
            String tId = (String) teacherCmb.getSelectedItem();
            TeacherDTO teacherDTO = ctrlTeacher.search(tId);
            DefaultTableModel dtm = (DefaultTableModel)teacherTbl.getModel();
            int j = 0;
            for(int i = 0; i< dtm.getRowCount(); i++){
                if(tId.equals(dtm.getValueAt(i, 0))){
                    j++;
                }
            }
            if(j==0){
                Object []tData = {tId, teacherDTO.getNameInit() };
                dtm.addRow(tData);
            }
        } catch (Exception ex) {
            Logger.getLogger(AddMeritBadge.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_teacherCmbActionPerformed

    private void teacherTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherTblMouseClicked
        DefaultTableModel dtm = (DefaultTableModel)teacherTbl.getModel();
        int index = teacherTbl.getSelectedRow();
        dtm.removeRow(index);
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_teacherTblMouseClicked

    private void teacherTblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherTblMouseEntered
        teacherTbl.setToolTipText("If you want to remove Qualified Teacher, then select row...");
    }//GEN-LAST:event_teacherTblMouseEntered

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    private void teacherCmbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherCmbMouseClicked
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_teacherCmbMouseClicked

    private void descriptionTxtAryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descriptionTxtAryMouseClicked
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_descriptionTxtAryMouseClicked

    private void badgeIdTxtFldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_badgeIdTxtFldMouseClicked
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_badgeIdTxtFldMouseClicked

    private void badgeNameTxtFldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_badgeNameTxtFldMouseClicked
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_badgeNameTxtFldMouseClicked

    private void jScrollPane4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane4MouseClicked
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_jScrollPane4MouseClicked

    private void cubScoutMrtLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cubScoutMrtLblMouseExited
        mouseExit(cubScoutMrtLbl);
    }//GEN-LAST:event_cubScoutMrtLblMouseExited

    private void scoutMrtLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scoutMrtLblMouseExited
        mouseExit(scoutMrtLbl);
    }//GEN-LAST:event_scoutMrtLblMouseExited

    private void roverMrtLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roverMrtLblMouseExited
        mouseExit(roverMrtLbl);
    }//GEN-LAST:event_roverMrtLblMouseExited

    private void cubScoutMrtLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cubScoutMrtLblMouseEntered
        mouseEnter(cubScoutMrtLbl);
    }//GEN-LAST:event_cubScoutMrtLblMouseEntered

    private void scoutMrtLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scoutMrtLblMouseEntered
        mouseEnter(scoutMrtLbl);
    }//GEN-LAST:event_scoutMrtLblMouseEntered

    private void roverMrtLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roverMrtLblMouseEntered
        mouseEnter(roverMrtLbl);
    }//GEN-LAST:event_roverMrtLblMouseEntered

    private void setTeacherId(){
        try {
            ArrayList<TeacherDTO> techerDTO = ctrlTeacher.getAll();
            for(TeacherDTO teacherDto : techerDTO){
                teacherCmb.addItem(teacherDto.getTId());
            }
        } catch (Exception ex) {
            Logger.getLogger(AddMeritBadge.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void mouseEnter(JLabel jLabel){
        jLabel.setBackground(new Color(0,114,222));
        jLabel.setForeground(Color.white);
    }
    
    private void mouseExit(JLabel jLabel){
        jLabel.setBackground(new Color(170,204,255));
        jLabel.setForeground(Color.black);
    }
    
    private String categoryId;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel badgeIdLbl;
    private javax.swing.JTextField badgeIdTxtFld;
    private javax.swing.JLabel badgeNameLbl;
    private javax.swing.JTextField badgeNameTxtFld;
    private javax.swing.JLabel cubScoutMrtLbl;
    private javax.swing.JTextArea descriptionTxtAry;
    private javax.swing.JLabel discriptionLbl;
    private javax.swing.JLabel headLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel roverLbl;
    private javax.swing.JLabel roverMrtLbl;
    private javax.swing.JLabel scoutMrtLbl;
    private javax.swing.JComboBox<String> teacherCmb;
    private javax.swing.JTable teacherTbl;
    private javax.swing.JLabel techersLbl;
    // End of variables declaration//GEN-END:variables
}
