/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.ijse.scouthq.view;

import edu.ijse.scouthq.controller.ControllerFactory;
import edu.ijse.scouthq.controller.custom.MemberController;
import edu.ijse.scouthq.controller.custom.SchoolController;
import edu.ijse.scouthq.dao.custom.impl.RegistrationCategoryDAOImpl;
import edu.ijse.scouthq.dto.MemberDTO;
import edu.ijse.scouthq.dto.SchoolDTO;
import static edu.ijse.scouthq.view.DiningArea.viewWhatPane;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Reshan Pubudu
 */
public class CubUpdatePane extends javax.swing.JPanel {

    SchoolController ctrlSchool;
    MemberController ctrlMbr;
    
    /** Creates new form CubUpdatePane */
    public CubUpdatePane() {
        initComponents();
        ctrlSchool = (SchoolController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.SCHOOL);
        ctrlMbr = (MemberController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.MEMBER);
        setDate();
        setSchoolId();
        setCubId();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fullNameLbl = new javax.swing.JLabel();
        joiningLbl = new javax.swing.JLabel();
        addressLbl = new javax.swing.JLabel();
        dateOfBirthLbl = new javax.swing.JLabel();
        nameInitTxtFld = new javax.swing.JTextField();
        dateOfBirthTxtFld = new javax.swing.JTextField();
        nameFullTxtFld = new javax.swing.JTextField();
        addressTxtFld = new javax.swing.JTextField();
        schoolTxtFld = new javax.swing.JTextField();
        schoolNameLbl = new javax.swing.JLabel();
        schoolIdCmb = new javax.swing.JComboBox<>();
        tpLbl = new javax.swing.JLabel();
        tpTxtFld = new javax.swing.JTextField();
        joiningDateTxtFld = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        finishBtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        nameInitLbl = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        schoolIdLbl1 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        schoolIdLbl2 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cubIdCmb = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setOpaque(false);

        jPanel1.setOpaque(false);

        fullNameLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fullNameLbl.setText("Fulll Name               ");

        joiningLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        joiningLbl.setText("Date Of Joining    ");

        addressLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addressLbl.setText("Address               ");

        dateOfBirthLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dateOfBirthLbl.setText("Date of Birth            ");

        nameInitTxtFld.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        nameInitTxtFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        nameInitTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameInitTxtFldActionPerformed(evt);
            }
        });

        dateOfBirthTxtFld.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        dateOfBirthTxtFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        dateOfBirthTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateOfBirthTxtFldActionPerformed(evt);
            }
        });

        nameFullTxtFld.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        nameFullTxtFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        nameFullTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFullTxtFldActionPerformed(evt);
            }
        });

        addressTxtFld.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        addressTxtFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        addressTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTxtFldActionPerformed(evt);
            }
        });

        schoolTxtFld.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        schoolTxtFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        schoolTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolTxtFldActionPerformed(evt);
            }
        });

        schoolNameLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        schoolNameLbl.setText("School Name");

        schoolIdCmb.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        schoolIdCmb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        schoolIdCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                schoolIdCmbItemStateChanged(evt);
            }
        });
        schoolIdCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolIdCmbActionPerformed(evt);
            }
        });

        tpLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tpLbl.setText("Telephon           ");

        tpTxtFld.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tpTxtFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        tpTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpTxtFldActionPerformed(evt);
            }
        });

        joiningDateTxtFld.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        joiningDateTxtFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        joiningDateTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joiningDateTxtFldActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        finishBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        finishBtn.setText("Finish");
        finishBtn.setOpaque(false);
        finishBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishBtnActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText(":");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText(":");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText(":");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText(":");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText(":");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText(":");

        nameInitLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameInitLbl.setText("Name (with initialize) ");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText(":");

        schoolIdLbl1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        schoolIdLbl1.setText("School Id   ");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText(":");

        schoolIdLbl2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        schoolIdLbl2.setText("Cub Scout Id");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText(":");

        cubIdCmb.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cubIdCmb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        cubIdCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cubIdCmbItemStateChanged(evt);
            }
        });
        cubIdCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cubIdCmbActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Remove Member");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(745, 745, 745)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(finishBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(schoolIdLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(cubIdCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tpLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(482, 482, 482)
                                .addComponent(schoolTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(joiningLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(schoolIdLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(schoolIdCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(tpTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(nameFullTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fullNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(joiningDateTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(332, 332, 332)
                                .addComponent(schoolNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(462, 462, 462)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameInitLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(addressTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dateOfBirthLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(dateOfBirthTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(nameInitTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(220, 220, 220))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cubIdCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(schoolIdLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(nameInitTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameInitLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fullNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(nameFullTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateOfBirthLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateOfBirthTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(addressTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(tpTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tpLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(schoolIdCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(schoolNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(schoolTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(schoolIdLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(joiningDateTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(joiningLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finishBtn)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(100, 100, 100))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameInitTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameInitTxtFldActionPerformed
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_nameInitTxtFldActionPerformed

    private void dateOfBirthTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateOfBirthTxtFldActionPerformed
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_dateOfBirthTxtFldActionPerformed

    private void nameFullTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFullTxtFldActionPerformed
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_nameFullTxtFldActionPerformed

    private void addressTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTxtFldActionPerformed
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_addressTxtFldActionPerformed

    private void schoolTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolTxtFldActionPerformed
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_schoolTxtFldActionPerformed

    private void schoolIdCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_schoolIdCmbItemStateChanged
        try {
            String sclId = (String) schoolIdCmb.getSelectedItem();
            SchoolDTO schoolDTO = ctrlSchool.search(sclId);
            schoolTxtFld.setText(schoolDTO.getName());
        } catch (Exception ex) {
            Logger.getLogger(BoyRegistrationPane.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_schoolIdCmbItemStateChanged

    private void schoolIdCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolIdCmbActionPerformed
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_schoolIdCmbActionPerformed

    private void tpTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpTxtFldActionPerformed
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_tpTxtFldActionPerformed

    private void joiningDateTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joiningDateTxtFldActionPerformed
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_joiningDateTxtFldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        viewWhatPane.setVisible(false);
        nameInitTxtFld.setText("");
        nameFullTxtFld.setText("");
        dateOfBirthTxtFld.setText("");
        addressTxtFld.setText("");
        tpTxtFld.setText("");
        joiningDateTxtFld.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void finishBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishBtnActionPerformed
        viewWhatPane.setVisible(false);
        
        
        /*ConformationForm.nameInit = nameInitTxtFld.getText();
        ConformationForm.nameFull = nameFullTxtFld.getText();
        ConformationForm.dateOfBirth = dateOfBirthTxtFld.getText();  //date
        ConformationForm.address = addressTxtFld.getText();
        ConformationForm.tp = Integer.parseInt(tpTxtFld.getText());
        ConformationForm.sclId = (String) schoolIdCmb.getSelectedItem();
        ConformationForm.joiningDate = joiningDateTxtFld.getText();  //date
        ConformationForm.registedDate = date;    // date

        ConformationForm.sc = "Cub Scout";
        new ConformationForm().setVisible(true);*/
    }//GEN-LAST:event_finishBtnActionPerformed

    private void cubIdCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cubIdCmbItemStateChanged
        loadDetails();
    }//GEN-LAST:event_cubIdCmbItemStateChanged

    private void cubIdCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cubIdCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cubIdCmbActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            boolean deleted = ctrlMbr.delete(((String)cubIdCmb.getSelectedItem()));
            if(deleted){
                JOptionPane.showMessageDialog(this, "Deleted member who name = "+nameInitTxtFld.getText()+" .");
                nameInitTxtFld.setText("");
                nameFullTxtFld.setText("");
                dateOfBirthTxtFld.setText("");  //date
                addressTxtFld.setText("");
                schoolTxtFld.setText("");
                tpTxtFld.setText("");
                joiningDateTxtFld.setText("");  //date
            }else{
                JOptionPane.showMessageDialog(this, "Sorry, Can't Delete member who name = "+nameInitTxtFld.getText()+" .");
            }
        } catch (Exception ex) {
            Logger.getLogger(BoyUpdatePane.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void setDate(){
        Date dt = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        date = sdf.format(dt);
    }
    
    private void setSchoolId(){
        try {
            ArrayList<SchoolDTO> schoolDTO = ctrlSchool.getAll();
            for(SchoolDTO schoolDto : schoolDTO){
                schoolIdCmb.addItem(schoolDto.getSclId());
            }
        } catch (Exception ex) {
            Logger.getLogger(BoyRegistrationPane.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void setCubId(){
            try {
                    ArrayList<MemberDTO> memberDTO =  new RegistrationCategoryDAOImpl().serchAndGetAllId("CSC01");
                    for(MemberDTO membrDto : memberDTO){
                        cubIdCmb.addItem(membrDto.getRegId());
                    }
            } catch (Exception ex) {
                Logger.getLogger(BoyRegistrationPane.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
    private void loadDetails() {
        
        try {
            MemberDTO memberDTOs = ctrlMbr.search(((String)cubIdCmb.getSelectedItem()));
            
            nameInitTxtFld.setText(memberDTOs.getNameInit());
            nameFullTxtFld.setText(memberDTOs.getNameFull());
            dateOfBirthTxtFld.setText(memberDTOs.getDateOfBirth());  //date
            addressTxtFld.setText(memberDTOs.getAddress());
            tpTxtFld.setText(""+memberDTOs.getTp());
            SchoolDTO sclName = ctrlSchool.search(memberDTOs.getSclId());
            schoolTxtFld.setText(sclName.getName());
            joiningDateTxtFld.setText(memberDTOs.getJoiningDate());
        } catch (Exception ex) {
            Logger.getLogger(BoyUpdatePane.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public String date;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLbl;
    public javax.swing.JTextField addressTxtFld;
    public javax.swing.JComboBox<String> cubIdCmb;
    private javax.swing.JLabel dateOfBirthLbl;
    public javax.swing.JTextField dateOfBirthTxtFld;
    private javax.swing.JButton finishBtn;
    private javax.swing.JLabel fullNameLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField joiningDateTxtFld;
    private javax.swing.JLabel joiningLbl;
    public javax.swing.JTextField nameFullTxtFld;
    private javax.swing.JLabel nameInitLbl;
    public javax.swing.JTextField nameInitTxtFld;
    public javax.swing.JComboBox<String> schoolIdCmb;
    private javax.swing.JLabel schoolIdLbl1;
    private javax.swing.JLabel schoolIdLbl2;
    private javax.swing.JLabel schoolNameLbl;
    public javax.swing.JTextField schoolTxtFld;
    private javax.swing.JLabel tpLbl;
    public javax.swing.JTextField tpTxtFld;
    // End of variables declaration//GEN-END:variables

}
