/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.scouthq.view;

import edu.ijse.scouthq.controller.ControllerFactory;
import edu.ijse.scouthq.controller.custom.MemberController;
import edu.ijse.scouthq.controller.custom.MeritBadgeController;
//import edu.ijse.scouthq.controller.custom.RoverController;
import edu.ijse.scouthq.controller.custom.TeacherController;
import edu.ijse.scouthq.dao.custom.impl.MemberDAOImpl;
import edu.ijse.scouthq.dao.custom.impl.MeritBadgeDAOImpl;
import edu.ijse.scouthq.dao.custom.impl.MeritBadgeTeacherDAOImpl;
import edu.ijse.scouthq.dao.custom.impl.RegistrationCategoryDAOImpl;
//import edu.ijse.scouthq.dao.custom.impl.RoverDAOImpl;
import edu.ijse.scouthq.dto.MemberDTO;
import edu.ijse.scouthq.dto.MeritBadgeDTO;
import edu.ijse.scouthq.dto.MeritBadgeTeacherDTO;
import edu.ijse.scouthq.dto.RoverDTO;
import edu.ijse.scouthq.dto.TeacherDTO;
import static edu.ijse.scouthq.view.DiningArea.viewWhatPane;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Reshan Pubudu
 */
public class MeritPassedPane extends javax.swing.JPanel {

    MemberController ctrlMember;
    //RoverController ctrlRover;
    MeritBadgeController ctrlMerit;
    TeacherController ctrlTeacher;
    
    /**
     * Creates new form MeritUpdatePane
     */
    public MeritPassedPane() {
        initComponents();
        ctrlMember = (MemberController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.MEMBER);
        //ctrlRover = (RoverController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.ROVER);
        ctrlMerit = (MeritBadgeController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.MERITBADGE);
        ctrlTeacher = (TeacherController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.TEACHER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        dateTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        teacherIdCmb = new javax.swing.JComboBox<>();
        teacherNameTxt = new javax.swing.JTextField();
        badgeNameTxt = new javax.swing.JTextField();
        badgeIdCmb = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        scoutIdlbl = new javax.swing.JLabel();
        regIdCmb = new javax.swing.JComboBox<>();
        scoutNameTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTxt = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Passed Date");

        dateTxt.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        dateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTxtActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Teacher  Id");

        teacherIdCmb.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        teacherIdCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                teacherIdCmbItemStateChanged(evt);
            }
        });
        teacherIdCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherIdCmbActionPerformed(evt);
            }
        });

        teacherNameTxt.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        teacherNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherNameTxtActionPerformed(evt);
            }
        });

        badgeNameTxt.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        badgeNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                badgeNameTxtActionPerformed(evt);
            }
        });

        badgeIdCmb.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        badgeIdCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                badgeIdCmbItemStateChanged(evt);
            }
        });
        badgeIdCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                badgeIdCmbActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Badge Id ");

        scoutIdlbl.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        scoutIdlbl.setText("Scout Id");

        regIdCmb.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        regIdCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                regIdCmbItemStateChanged(evt);
            }
        });
        regIdCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regIdCmbActionPerformed(evt);
            }
        });

        scoutNameTxt.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        scoutNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoutNameTxtActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Finish");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Description");

        descriptionTxt.setColumns(20);
        descriptionTxt.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        descriptionTxt.setRows(5);
        descriptionTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descriptionTxtMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(descriptionTxt);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText(":");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText(":");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText(":");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText(":");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText(":");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(590, 590, 590)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scoutIdlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(teacherIdCmb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(badgeIdCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(regIdCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(teacherNameTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(badgeNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(scoutNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(235, 235, 235))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scoutIdlbl)
                            .addComponent(jLabel1))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel6)))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(regIdCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(badgeIdCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(teacherIdCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(scoutNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(badgeNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(teacherNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTxtActionPerformed
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_dateTxtActionPerformed

    private void teacherIdCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherIdCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherIdCmbActionPerformed

    private void badgeIdCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_badgeIdCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_badgeIdCmbActionPerformed

    private void regIdCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regIdCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regIdCmbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        viewWhatPane.setVisible(false);
        String regId = (String) regIdCmb.getSelectedItem();
        String badgeId = (String) badgeIdCmb.getSelectedItem();
        String tId = (String) teacherIdCmb.getSelectedItem();
        String date = dateTxt.getText();
        String description = descriptionTxt.getText();
        
        ConformationForm.passRegId = regId;
        ConformationForm.passBadgeId = badgeId;
        ConformationForm.passTeacher = tId;
        ConformationForm.passDate = date;
        ConformationForm.passDescription = description;
        
        ConformationForm.sc = "Member Merit Badge Update";
        new ConformationForm().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void teacherNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherNameTxtActionPerformed
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_teacherNameTxtActionPerformed

    private void badgeNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_badgeNameTxtActionPerformed
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_badgeNameTxtActionPerformed

    private void regIdCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_regIdCmbItemStateChanged
        viewWhatPane.setVisible(false);
        try {
            String id = (String) regIdCmb.getSelectedItem();
            String cat = (String) NewBadgePassedPane.catCmb.getSelectedItem();
//            if(cat.equals("Cub Scout")|| cat.equals("Boy Scout")||cat.equals("Girl Scout")){
                MemberDTO memberDTO = ctrlMember.search(id);
                String name = memberDTO.getNameInit();     
                scoutNameTxt.setText(name);
//            }
//            if(cat.equals("Rover Scout")){
//                RoverDTO roverDTO = ctrlRover.search(id);
//                String name = roverDTO.getNameInit();
//                scoutNameTxt.setText(name);
//            }
            
        } catch (Exception ex) {
            Logger.getLogger(CorePassedPane.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_regIdCmbItemStateChanged

    private void badgeIdCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_badgeIdCmbItemStateChanged
        viewWhatPane.setVisible(false);
        try {
            String badgeId = (String) badgeIdCmb.getSelectedItem();
            MeritBadgeDTO meritBadgeDTO = ctrlMerit.search(badgeId);
            String badgeName = meritBadgeDTO.getBadgeName();
            badgeNameTxt.setText(badgeName);
            teacherIdCmb.removeAllItems();
            /////////////////////////////////////////////////////////////
            
            
            
            ArrayList<MeritBadgeTeacherDTO> meritBadgeTeacherDTOs = new MeritBadgeTeacherDAOImpl().searchAndGetAllId(badgeId);
            for(MeritBadgeTeacherDTO meritBadgeTeacherDTO : meritBadgeTeacherDTOs){
                teacherIdCmb.addItem(meritBadgeTeacherDTO.gettId());
            }
            
            
            
            /////////////////////////////////////////////////////////////
        } catch (Exception ex) {
            Logger.getLogger(CorePassedPane.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_badgeIdCmbItemStateChanged

    private void teacherIdCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_teacherIdCmbItemStateChanged
        viewWhatPane.setVisible(false);
        try {
            String teacherId = (String) teacherIdCmb.getSelectedItem();
            TeacherDTO teacherDTO = ctrlTeacher.search(teacherId);
            teacherNameTxt.setText(teacherDTO.getNameInit());
        } catch (Exception ex) {
            Logger.getLogger(MeritPassedPane.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_teacherIdCmbItemStateChanged

    private void scoutNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoutNameTxtActionPerformed
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_scoutNameTxtActionPerformed

    private void descriptionTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descriptionTxtMouseClicked
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_descriptionTxtMouseClicked

    public void setAllId(String type){
        
            try {
                String cat = "";
                if(type.equals("Cub Scout")){
                    cat = "CSC01";
                }
                if(type.equals("Boy Scout")){
                    cat = "BSC01";
                }
                if(type.equals("Girl Scout")){
                    cat = "GSC01";
                }
                if(type.equals("Rover Scout")){
                    cat = "RSC01";
                }
//                if(type.equals("Cub Scout")|| type.equals("Boy Scout")||type.equals("Girl Scout")){
                    ArrayList<MemberDTO> memberDTO =  new RegistrationCategoryDAOImpl().serchAndGetAllId(cat);
                    for(MemberDTO membrDto : memberDTO){
                        regIdCmb.addItem(membrDto.getRegId());
                    }
//                }
//                if(type.equals("Rover Scout")){
//                    ArrayList<MemberDTO> memberDTO =  new MemberDAOImpl().serchAndGetAllId(cat);
//                    for(RoverDTO roverDto : roverDTO){
//                        regIdCmb.addItem(roverDto.getRegId());
//                    }
//                }
            } catch (Exception ex) {
                Logger.getLogger(BoyRegistrationPane.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
    public void setAllMeritBadgeId(String type){
            try {
                String cat = "";
                if(type.equals("Cub Scout")){
                    cat = "CSC01";
                }
                if(type.equals("Boy Scout")||type.equals("Girl Scout")){
                    cat = "BSC01";
                }
                if(type.equals("Rover Scout")){
                    cat = "RSC01";
                }
                ArrayList<MeritBadgeDTO> meritBadgeDTO = new MeritBadgeDAOImpl().searchAndGetAllId(cat);
                for(MeritBadgeDTO meritBadgeDTO1 : meritBadgeDTO){
                    badgeIdCmb.addItem(meritBadgeDTO1.getBadgeId());
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(BoyRegistrationPane.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> badgeIdCmb;
    private javax.swing.JTextField badgeNameTxt;
    private javax.swing.JTextField dateTxt;
    private javax.swing.JTextArea descriptionTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> regIdCmb;
    public static javax.swing.JLabel scoutIdlbl;
    private javax.swing.JTextField scoutNameTxt;
    private javax.swing.JComboBox<String> teacherIdCmb;
    private javax.swing.JTextField teacherNameTxt;
    // End of variables declaration//GEN-END:variables
}
