/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.scouthq.view;

import static edu.ijse.scouthq.view.DiningArea.viewWhatPane;

/**
 *
 * @author Reshan Pubudu
 */
public class NewBadgePassedPane extends javax.swing.JPanel {

    /**
     * Creates new form UpdateDetails
     */
    public NewBadgePassedPane() {
        initComponents();
        coreBadgeRd.setSelected(true);
        loadCorePassedPane("Boy Scout Id");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        headLbl = new javax.swing.JLabel();
        badgeUpdatePane = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        coreBadgeRd = new javax.swing.JRadioButton();
        catCmb = new javax.swing.JComboBox<>();
        meritBadgeRd = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        setOpaque(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setOpaque(false);
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        headLbl.setBackground(new java.awt.Color(1, 229, 0));
        headLbl.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        headLbl.setForeground(new java.awt.Color(0, 0, 255));
        headLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        badgeUpdatePane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        badgeUpdatePane.setOpaque(false);
        badgeUpdatePane.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(170, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Badge Type   ");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Category   :");

        coreBadgeRd.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(coreBadgeRd);
        coreBadgeRd.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        coreBadgeRd.setText("Core Badge");
        coreBadgeRd.setOpaque(false);
        coreBadgeRd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coreBadgeRdActionPerformed(evt);
            }
        });

        catCmb.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        catCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boy Scout", "Cub Scout", "Girl Scout", "Rover Scout" }));
        catCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                catCmbItemStateChanged(evt);
            }
        });

        meritBadgeRd.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(meritBadgeRd);
        meritBadgeRd.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        meritBadgeRd.setText("Merit Badge");
        meritBadgeRd.setOpaque(false);
        meritBadgeRd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meritBadgeRdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(catCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coreBadgeRd)
                    .addComponent(meritBadgeRd))
                .addContainerGap(653, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(catCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(coreBadgeRd, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(meritBadgeRd, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(headLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(badgeUpdatePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(977, 977, 977))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(headLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(badgeUpdatePane, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE))
        );

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/scouthq/image/winter-stripes-background11.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1130, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1120, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void coreBadgeRdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coreBadgeRdActionPerformed
        loadPanes();
    }//GEN-LAST:event_coreBadgeRdActionPerformed

    private void meritBadgeRdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meritBadgeRdActionPerformed
        loadPanes();
    }//GEN-LAST:event_meritBadgeRdActionPerformed

    private void catCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_catCmbItemStateChanged
        loadPanes();
    }//GEN-LAST:event_catCmbItemStateChanged
    
    public void loadCorePassedPane(String type){
        headLbl.setText(type+"s Core Badges Passed");
        badgeUpdatePane.removeAll();
        CorePassedPane coreUpdatePane = new CorePassedPane();
        coreUpdatePane.setAllId(type);
        coreUpdatePane.setAllCoreBadgeId(type);
        coreUpdatePane.scoutIdlbl.setText(type+" Id");
        coreUpdatePane.setSize(badgeUpdatePane.getSize());
        badgeUpdatePane.add(coreUpdatePane);
        badgeUpdatePane.updateUI();
        badgeUpdatePane.updateUI();
    }

    public void loadMeritPassedPane(String type){
        headLbl.setText(type+"s Merit Badges Passed");
        badgeUpdatePane.removeAll();
        MeritPassedPane meritUpdatePane = new MeritPassedPane();
        meritUpdatePane.setAllId(type);
        meritUpdatePane.setAllMeritBadgeId(type);
        meritUpdatePane.scoutIdlbl.setText(type+" Id");
        meritUpdatePane.setSize(badgeUpdatePane.getSize());
        badgeUpdatePane.add(meritUpdatePane);
        badgeUpdatePane.updateUI();
        badgeUpdatePane.updateUI();
    }
    
    public void loadPanes(){
        if (coreBadgeRd.isSelected()) {
            meritOrCore = "core";
        }
        if (meritBadgeRd.isSelected()) {
            meritOrCore = "merit";
        }
        String typee = (String) catCmb.getSelectedItem();
        String type = "";
        if(typee.equals("Cub Scout")){
            type = typee;
        }
        if(typee.equals("Boy Scout")){
            type = typee;
        }
        if(typee.equals("Girl Scout")){
            type = typee;
        }
        if(typee.equals("Rover Scout")){
            type = typee;
        }
        if(!type.equals("")){
            if(meritOrCore.equals("core")){
                loadCorePassedPane(type);
            }
            if(meritOrCore.equals("merit")){
                loadMeritPassedPane(type);
            }
        }
    }
    
    String meritOrCore;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel badgeUpdatePane;
    private javax.swing.ButtonGroup buttonGroup2;
    public static javax.swing.JComboBox<String> catCmb;
    private javax.swing.JRadioButton coreBadgeRd;
    public static javax.swing.JLabel headLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton meritBadgeRd;
    // End of variables declaration//GEN-END:variables
}
