/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.scouthq.view;

import edu.ijse.scouthq.controller.ControllerFactory;
import edu.ijse.scouthq.controller.custom.SchoolController;
import edu.ijse.scouthq.dto.SchoolDTO;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Reshan Pubudu
 */
public class Registration extends javax.swing.JPanel {

    private final SchoolController ctrlSchool;
    
    /**
     * Creates new form scoutRegistration
     */
    public Registration() {
        initComponents();
        setDate();
        ctrlSchool = (SchoolController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.SCHOOL);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        headPane = new javax.swing.JLabel();
        catpane = new javax.swing.JPanel();
        boyLbl = new javax.swing.JLabel();
        girlLbl = new javax.swing.JLabel();
        roverLbl = new javax.swing.JLabel();
        teacherLbl = new javax.swing.JLabel();
        cubLbl = new javax.swing.JLabel();
        schoolLbl = new javax.swing.JLabel();
        regPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setOpaque(false);

        headPane.setBackground(new java.awt.Color(51, 51, 51));
        headPane.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        headPane.setForeground(new java.awt.Color(0, 0, 255));
        headPane.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        catpane.setBackground(new java.awt.Color(51, 51, 51, 70));
        catpane.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(0, 0, 0)));

        boyLbl.setBackground(new java.awt.Color(170, 204, 255));
        boyLbl.setDisplayedMnemonic('b');
        boyLbl.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        boyLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boyLbl.setText("Boy Scout");
        boyLbl.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        boyLbl.setName("catagory"); // NOI18N
        boyLbl.setOpaque(true);
        boyLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boyLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boyLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boyLblMouseExited(evt);
            }
        });

        girlLbl.setBackground(new java.awt.Color(170, 204, 255));
        girlLbl.setDisplayedMnemonic('g');
        girlLbl.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        girlLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        girlLbl.setText(" Girl Scout");
        girlLbl.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        girlLbl.setName("catagory"); // NOI18N
        girlLbl.setOpaque(true);
        girlLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                girlLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                girlLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                girlLblMouseExited(evt);
            }
        });

        roverLbl.setBackground(new java.awt.Color(170, 204, 255));
        roverLbl.setDisplayedMnemonic('r');
        roverLbl.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        roverLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roverLbl.setText("Rover");
        roverLbl.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        roverLbl.setName("catagory"); // NOI18N
        roverLbl.setOpaque(true);
        roverLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roverLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                roverLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                roverLblMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                roverLblMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                roverLblMouseReleased(evt);
            }
        });

        teacherLbl.setBackground(new java.awt.Color(170, 204, 255));
        teacherLbl.setDisplayedMnemonic('t');
        teacherLbl.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        teacherLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        teacherLbl.setText("Teacher");
        teacherLbl.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        teacherLbl.setName("catagory"); // NOI18N
        teacherLbl.setOpaque(true);
        teacherLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacherLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                teacherLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                teacherLblMouseExited(evt);
            }
        });

        cubLbl.setBackground(new java.awt.Color(170, 204, 255));
        cubLbl.setDisplayedMnemonic('c');
        cubLbl.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        cubLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cubLbl.setText(" Cub Scout");
        cubLbl.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        cubLbl.setName("catagory"); // NOI18N
        cubLbl.setOpaque(true);
        cubLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cubLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cubLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cubLblMouseExited(evt);
            }
        });

        schoolLbl.setBackground(new java.awt.Color(170, 204, 255));
        schoolLbl.setDisplayedMnemonic('s');
        schoolLbl.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        schoolLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        schoolLbl.setText("School");
        schoolLbl.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        schoolLbl.setName("catagory"); // NOI18N
        schoolLbl.setOpaque(true);
        schoolLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                schoolLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                schoolLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                schoolLblMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                schoolLblMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                schoolLblMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout catpaneLayout = new javax.swing.GroupLayout(catpane);
        catpane.setLayout(catpaneLayout);
        catpaneLayout.setHorizontalGroup(
            catpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catpaneLayout.createSequentialGroup()
                .addComponent(cubLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(boyLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(girlLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(roverLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(teacherLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(schoolLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        catpaneLayout.setVerticalGroup(
            catpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catpaneLayout.createSequentialGroup()
                .addGroup(catpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cubLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boyLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(girlLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roverLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(catpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(teacherLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(schoolLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        regPane.setBackground(new java.awt.Color(51, 153, 255));
        regPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        regPane.setOpaque(false);
        regPane.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1099, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(catpane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(headPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(headPane, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(catpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regPane, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/scouthq/image/winter-stripes-background11.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1120, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void schoolLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schoolLblMouseClicked
        SchoolRegistrationPane sclRegPane = new SchoolRegistrationPane();
        sclRegPane.setSize(regPane.getSize());
        regPane.removeAll();
        regPane.add(sclRegPane);
        headPane.setText("School Registration");
        regPane.updateUI();
        checkMouseEvent(15,1);
    }//GEN-LAST:event_schoolLblMouseClicked

    private void cubLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cubLblMouseClicked
        regPane.removeAll();
        CubRegistrationPane cubRegPane = new CubRegistrationPane();
        cubRegPane.setSize(regPane.getSize());
        regPane.removeAll();
        regPane.add(cubRegPane);
        headPane.setText("Cub Scout Registration");
        regPane.updateUI();
        checkMouseEvent(10,1);
    }//GEN-LAST:event_cubLblMouseClicked

    private void schoolLblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schoolLblMousePressed
        
    }//GEN-LAST:event_schoolLblMousePressed

    private void roverLblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roverLblMousePressed
        
    }//GEN-LAST:event_roverLblMousePressed

    private void roverLblMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roverLblMouseReleased
        
    }//GEN-LAST:event_roverLblMouseReleased

    private void roverLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roverLblMouseClicked
        regPane.removeAll();
        RoverRegistrationPane rvrRegPane = new RoverRegistrationPane();
        rvrRegPane.setSize(regPane.getSize());
        regPane.add(rvrRegPane);
        headPane.setText("Rover Scout Registration");
        //regPane.repaint();
        //regPane.revalidate();
        regPane.updateUI();
        checkMouseEvent(13,1);
    }//GEN-LAST:event_roverLblMouseClicked

    private void schoolLblMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schoolLblMouseReleased
        
    }//GEN-LAST:event_schoolLblMouseReleased

    private void boyLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boyLblMouseClicked
        loadScoutRegistrationPane();
        checkMouseEvent(11,1);
    }//GEN-LAST:event_boyLblMouseClicked

    private void girlLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_girlLblMouseClicked
        regPane.removeAll();
        GirlRegistrationPane grlRegPane = new GirlRegistrationPane();
        grlRegPane.setSize(regPane.getSize());
        regPane.add(grlRegPane);
        headPane.setText("Girl Scout Registration");
        regPane.updateUI();
        checkMouseEvent(12,1);
    }//GEN-LAST:event_girlLblMouseClicked

    private void teacherLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherLblMouseClicked
        regPane.removeAll();
        TeacherRegistrationPane teacherRegPane = new TeacherRegistrationPane();
        teacherRegPane.setSize(regPane.getSize());
        teacherRegPane.setVisible(true);
        regPane.add(teacherRegPane);
        headPane.setText("Teachers Registration");
        //regPane.repaint();
        //regPane.revalidate();
        regPane.updateUI();
        checkMouseEvent(14,1);
    }//GEN-LAST:event_teacherLblMouseClicked

    private void cubLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cubLblMouseEntered
        checkMouseEvent(10,2);
    }//GEN-LAST:event_cubLblMouseEntered

    private void boyLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boyLblMouseEntered
        checkMouseEvent(11,2);
    }//GEN-LAST:event_boyLblMouseEntered

    private void girlLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_girlLblMouseEntered
        checkMouseEvent(12,2);
    }//GEN-LAST:event_girlLblMouseEntered

    private void roverLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roverLblMouseEntered
        checkMouseEvent(13,2);
    }//GEN-LAST:event_roverLblMouseEntered

    private void teacherLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherLblMouseEntered
        checkMouseEvent(14,2);
    }//GEN-LAST:event_teacherLblMouseEntered

    private void schoolLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schoolLblMouseEntered
        checkMouseEvent(15,2);
    }//GEN-LAST:event_schoolLblMouseEntered

    private void cubLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cubLblMouseExited
        checkMouseEvent(10,3);
    }//GEN-LAST:event_cubLblMouseExited

    private void boyLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boyLblMouseExited
        checkMouseEvent(11,3);
    }//GEN-LAST:event_boyLblMouseExited

    private void girlLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_girlLblMouseExited
        checkMouseEvent(12,3);
    }//GEN-LAST:event_girlLblMouseExited

    private void roverLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roverLblMouseExited
        checkMouseEvent(13,3);
    }//GEN-LAST:event_roverLblMouseExited

    private void teacherLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherLblMouseExited
        checkMouseEvent(14,3);
    }//GEN-LAST:event_teacherLblMouseExited

    private void schoolLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schoolLblMouseExited
        checkMouseEvent(15,3);
    }//GEN-LAST:event_schoolLblMouseExited

    public void loadScoutRegistrationPane(){
        regPane.removeAll();
        BoyRegistrationPane scRegPane = new BoyRegistrationPane();
        scRegPane.setSize(regPane.getSize());
        regPane.add(scRegPane);
        regPane.updateUI();
        scRegPane.setVisible(true);
        headPane.setText("Boy Scout Registration");
    }
    
    private void setDate(){
        Date dt = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        date = sdf.format(dt);
    }
    
    private void setAllId(){
        try {
            ArrayList<SchoolDTO> schoolDTO = ctrlSchool.getAll();
            for(SchoolDTO schoolDto : schoolDTO){
                //schoolIdCmb.addItem(schoolDto.getSclId());
            }
        } catch (Exception ex) {
            Logger.getLogger(BoyRegistrationPane.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void checkMouseEvent(int clicked, int event){
        JLabel catLbl = new JLabel();
        switch (clicked) {
            case 10:
                catLbl = cubLbl;
                break;
            case 11:
                catLbl = boyLbl;
                break;
            case 12:
                catLbl = girlLbl;
                break;
            case 13:
                catLbl = roverLbl;
                break;
            case 14:
                catLbl = teacherLbl;
                break;
            case 15:
                catLbl = schoolLbl;
                break;
            default:
                break;
        }
        switch (event) {
            case 1:
                checkMouseEvent(clickedLbl,4);
                mouseClick(catLbl);
                clickedLbl = clicked;
                break;
            case 2:
                if(clickedLbl !=clicked){
                    mouseEnted(catLbl);
                }   break;
            case 3:
                if(clickedLbl !=clicked){
                    mouseExited(catLbl);
                }   break;
            case 4:
                mouseExited(catLbl);
                break;
            default:
                break;
        }
    }
    
    private void mouseClick(JLabel catLbl){
        catLbl.setBackground(new Color(80, 80, 250));
        catLbl.setForeground(Color.white);
    }
    
    private void mouseEnted(JLabel catLbl){
        catLbl.setBackground(new Color(100, 140, 250));
        catLbl.setForeground(Color.black);
    }
    
    private void mouseExited(JLabel catLbl){
        catLbl.setBackground(new Color(170,204,255));
        catLbl.setForeground(Color.black);
    }
    
    /*private void setBtnMouseEventLbl(JPanel jPanel){
        Component[] components = jPanel.getComponents();

        for (Component component : components) {

            if (component instanceof JLabel) {
                JLabel lbl = (JLabel) component;

                if (lbl.getName() != null && lbl.getName().equals("catagory")) {

                    lbl.addMouseListener(new MouseAdapter() {

                        @Override
                        public void mouseEntered(MouseEvent e) {
                            lbl.setBackground(new Color(0,114,222));
                            lbl.setForeground(Color.WHITE);
                        }

                        @Override
                        public void mouseExited(MouseEvent e) {
                            lbl.setBackground(new Color(170,204,255));
                            lbl.setForeground(Color.BLACK);
                        }

                    });
                }
            }
        }
    }*/
    
    private int clickedLbl;
    
    private String date;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel boyLbl;
    private javax.swing.JPanel catpane;
    private javax.swing.JLabel cubLbl;
    private javax.swing.JLabel girlLbl;
    public static javax.swing.JLabel headPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel regPane;
    private javax.swing.JLabel roverLbl;
    private javax.swing.JLabel schoolLbl;
    private javax.swing.JLabel teacherLbl;
    // End of variables declaration//GEN-END:variables

}
