/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.scouthq.view;

import static edu.ijse.scouthq.view.DiningArea.viewWhatPane;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Reshan Pubudu
 */
public class SchoolRegistrationPane extends javax.swing.JPanel {

    /**
     * Creates new form SchoolRegistrationPane
     */
    public SchoolRegistrationPane() {
        initComponents();
        setDate();
        setStartedYear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startedDateLbl = new javax.swing.JLabel();
        addressLbl = new javax.swing.JLabel();
        addressTxtFld = new javax.swing.JTextField();
        schoolTxtFld = new javax.swing.JTextField();
        schoolNameLbl = new javax.swing.JLabel();
        tpLbl = new javax.swing.JLabel();
        tpTxtFld = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        finishBtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        descriptionLbl = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTxtFld = new javax.swing.JTextArea();
        joinYearCmb = new javax.swing.JComboBox<>();
        joinMonthCmb = new javax.swing.JComboBox<>();
        joinDayCmb = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);

        startedDateLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        startedDateLbl.setText("Date Of Started    ");

        addressLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addressLbl.setText("Address               ");

        addressTxtFld.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        addressTxtFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        addressTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTxtFldActionPerformed(evt);
            }
        });

        schoolTxtFld.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        schoolTxtFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        schoolTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolTxtFldActionPerformed(evt);
            }
        });

        schoolNameLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        schoolNameLbl.setText("School Name");

        tpLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tpLbl.setText("Telephon           ");

        tpTxtFld.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tpTxtFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        tpTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpTxtFldActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        finishBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        finishBtn.setText("Finish");
        finishBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishBtnActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText(":");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText(":");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText(":");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText(":");

        descriptionLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        descriptionLbl.setText("Descripton");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText(":");

        descriptionTxtFld.setColumns(20);
        descriptionTxtFld.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        descriptionTxtFld.setRows(5);
        descriptionTxtFld.setBorder(null);
        descriptionTxtFld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descriptionTxtFldMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(descriptionTxtFld);

        joinYearCmb.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        joinYearCmb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        joinYearCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                joinYearCmbItemStateChanged(evt);
            }
        });

        joinMonthCmb.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        joinMonthCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "Juny", "July", "August", "September", "October", "November", "December" }));
        joinMonthCmb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        joinMonthCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                joinMonthCmbItemStateChanged(evt);
            }
        });
        joinMonthCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinMonthCmbActionPerformed(evt);
            }
        });

        joinDayCmb.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        joinDayCmb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        joinDayCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                joinDayCmbItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(900, 900, 900)
                        .addComponent(jButton1)
                        .addGap(10, 10, 10)
                        .addComponent(finishBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(schoolNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(schoolTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(addressTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tpLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(tpTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(descriptionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(startedDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(joinYearCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(joinMonthCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(joinDayCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(schoolNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(schoolTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tpLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tpTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startedDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(joinYearCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(joinMonthCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(joinDayCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(finishBtn))
                .addGap(100, 100, 100))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addressTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTxtFldActionPerformed
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_addressTxtFldActionPerformed

    private void schoolTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolTxtFldActionPerformed
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_schoolTxtFldActionPerformed

    private void tpTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpTxtFldActionPerformed
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_tpTxtFldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        viewWhatPane.setVisible(false);
        schoolTxtFld.setText("");
        addressTxtFld.setText("");
        tpTxtFld.setText("");
        descriptionTxtFld.setText(""); // Add Description 
        //startedDateTxtFld.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void finishBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishBtnActionPerformed
        ConformationForm.sc = "School";
        new ConformationForm().setVisible(true);
        
        int i = 0;
        
        String sclName = schoolTxtFld.getText().trim();
        String address = addressTxtFld.getText().trim();
        String tp  = tpTxtFld.getText().trim();
        String description = descriptionTxtFld.getText();
        String startMonth = getMonthNo((String) joinMonthCmb.getSelectedItem());
        String startedDate = joinYearCmb.getSelectedItem()+"-"+startMonth+"-"+joinDayCmb.getSelectedItem();
        
        if(!sclName.equals("")){
            i++;
        }
        else{
            JOptionPane.showMessageDialog(this,"Sorry, Pleace enter a valid Name");
        }
        
        if(!address.equals(null)){
            i++;
        }
        
        if(tp.matches("[0]\\d{9}")){
            i++;
        }
        else{
            JOptionPane.showMessageDialog(this,"Sorry, Pleace enter a valid Telephon Number");
        }
        
        if(description.equals(null)){
            description = "";
        }
        
        if(i==3){ 
            ConformationForm.sclName = sclName;
            ConformationForm.address = address;
            ConformationForm.tp = tp;
            ConformationForm.description = description;
            ConformationForm.startedDate = startedDate;  
            ConformationForm.registedDate = date;

            ConformationForm.sc = "School";
            new ConformationForm().setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this,"Sorry, Pleace Check and Re-enter a Valied Details");
        }
    }//GEN-LAST:event_finishBtnActionPerformed

    private void descriptionTxtFldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descriptionTxtFldMouseClicked
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_descriptionTxtFldMouseClicked

    private void joinYearCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_joinYearCmbItemStateChanged
        setDay((String) joinMonthCmb.getSelectedItem(),Integer.parseInt((String) joinYearCmb.getSelectedItem()),joinDayCmb);
    }//GEN-LAST:event_joinYearCmbItemStateChanged

    private void joinMonthCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_joinMonthCmbItemStateChanged
        setDay((String) joinMonthCmb.getSelectedItem(),Integer.parseInt((String) joinYearCmb.getSelectedItem()),joinDayCmb);
    }//GEN-LAST:event_joinMonthCmbItemStateChanged

    private void joinMonthCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinMonthCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_joinMonthCmbActionPerformed

    private void joinDayCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_joinDayCmbItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_joinDayCmbItemStateChanged

    
    private void setDate(){
        Date dt = new Date();
        SimpleDateFormat sdfDate = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat sdfYear = new SimpleDateFormat("yyyy");
        SimpleDateFormat sdfMonth = new SimpleDateFormat("MM");
        SimpleDateFormat sdfDay = new SimpleDateFormat("dd");
        date = sdfDate.format(dt);
        year = sdfYear.format(dt);
        month = sdfMonth.format(dt);
        day = sdfDay.format(dt);
    }
    
    private void setStartedYear(){
        int nowYer = Integer.parseInt(year);
        int startYer = nowYer;
        joinYearCmb.removeAllItems();
        for(;startYer>=1914;startYer--){
            if(startYer<=nowYer){
                joinYearCmb.addItem(""+startYer);
            }
            else break;
        }
        
        setDay((String) joinMonthCmb.getSelectedItem(),Integer.parseInt((String) joinYearCmb.getSelectedItem()),joinDayCmb);
    }
    
    private void setDay(String mnth,int yer,JComboBox cmb){
        int i = 0;
        switch (mnth){
            case "January" :
            case "March" :
            case "May" :
            case "July" :
            case "August" :
            case "October" :
            case "December" : i = 31;
            break;
            case "February" : i = 28;
            break;
            case "April" :
            case "Juny" :
            case "September" :
            case "November" : i = 30;
            break;
        }
        if(yer%4==0&& mnth.equals("February")){
            i = 29;
        }
        cmb.removeAllItems();
        if(i!=0){
            for(int k = i; k>=1; k--){
                cmb.addItem(""+k);
            }
        }
    }
    
    private String getMonthNo(String month){
        switch (month){
            case "January" : month = "1";
            break;
            case "February" : month = "2";
            break;
            case "March" : month = "3";
            break;
            case "April" : month = "4";
            break;
            case "May" : month = "5";
            break;
            case "Juny" : month = "6";
            break;
            case "July" : month = "7";
            break;
            case "August" : month = "8";
            break;
            case "September" : month = "9";
            break;
            case "October" : month = "10";
            break;
            case "November" : month = "11";
            break;
            case "December" : month = "12";
            break;
        }
        return month;
    }
    
    private String date;
    private String year;
    private String month;
    private String day;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLbl;
    public javax.swing.JTextField addressTxtFld;
    private javax.swing.JLabel descriptionLbl;
    private javax.swing.JTextArea descriptionTxtFld;
    private javax.swing.JButton finishBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> joinDayCmb;
    private javax.swing.JComboBox<String> joinMonthCmb;
    private javax.swing.JComboBox<String> joinYearCmb;
    private javax.swing.JLabel schoolNameLbl;
    public javax.swing.JTextField schoolTxtFld;
    private javax.swing.JLabel startedDateLbl;
    private javax.swing.JLabel tpLbl;
    public javax.swing.JTextField tpTxtFld;
    // End of variables declaration//GEN-END:variables
}
