/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.scouthq.view;

import static edu.ijse.scouthq.view.DiningArea.viewWhatPane;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Reshan Pubudu
 */
public class SchoolUpdatePane extends javax.swing.JPanel {

    /**
     * Creates new form SchoolUpdatePane
     */
    public SchoolUpdatePane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        startedDateLbl = new javax.swing.JLabel();
        addressLbl = new javax.swing.JLabel();
        addressTxtFld = new javax.swing.JTextField();
        schoolTxtFld = new javax.swing.JTextField();
        schoolNameLbl = new javax.swing.JLabel();
        tpLbl = new javax.swing.JLabel();
        tpTxtFld = new javax.swing.JTextField();
        startedDateTxtFld = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        finishBtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        descriptionLbl = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTxtFld = new javax.swing.JTextArea();
        schoolIdLbl3 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        schoolIdCmb1 = new javax.swing.JComboBox<>();

        setOpaque(false);

        jPanel1.setOpaque(false);

        startedDateLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        startedDateLbl.setText("Date Of Started    ");

        addressLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addressLbl.setText("Address               ");

        addressTxtFld.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        addressTxtFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        addressTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTxtFldActionPerformed(evt);
            }
        });

        schoolTxtFld.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        schoolTxtFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        schoolTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolTxtFldActionPerformed(evt);
            }
        });

        schoolNameLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        schoolNameLbl.setText("School Name");

        tpLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tpLbl.setText("Telephon           ");

        tpTxtFld.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tpTxtFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        tpTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpTxtFldActionPerformed(evt);
            }
        });

        startedDateTxtFld.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        startedDateTxtFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        startedDateTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startedDateTxtFldActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        finishBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        finishBtn.setText("Finish");
        finishBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishBtnActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText(":");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText(":");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText(":");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText(":");

        descriptionLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        descriptionLbl.setText("Descripton");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText(":");

        descriptionTxtFld.setColumns(20);
        descriptionTxtFld.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        descriptionTxtFld.setRows(5);
        descriptionTxtFld.setBorder(null);
        descriptionTxtFld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descriptionTxtFldMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(descriptionTxtFld);

        schoolIdLbl3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        schoolIdLbl3.setText("School Id");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText(":");

        schoolIdCmb1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        schoolIdCmb1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        schoolIdCmb1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                schoolIdCmb1ItemStateChanged(evt);
            }
        });
        schoolIdCmb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolIdCmb1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(900, 900, 900)
                        .addComponent(jButton1)
                        .addGap(10, 10, 10)
                        .addComponent(finishBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(schoolNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(schoolTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(addressTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tpLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(tpTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(startedDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(startedDateTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(descriptionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(schoolIdLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(schoolIdCmb1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(110, 110, 110))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(schoolIdCmb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(schoolIdLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(schoolNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(schoolTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tpLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tpTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startedDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startedDateTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(finishBtn))
                .addGap(100, 100, 100))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addressTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTxtFldActionPerformed
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_addressTxtFldActionPerformed

    private void schoolTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolTxtFldActionPerformed
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_schoolTxtFldActionPerformed

    private void tpTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpTxtFldActionPerformed
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_tpTxtFldActionPerformed

    private void startedDateTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startedDateTxtFldActionPerformed
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_startedDateTxtFldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        viewWhatPane.setVisible(false);
        schoolTxtFld.setText("");
        addressTxtFld.setText("");
        tpTxtFld.setText("");
        descriptionTxtFld.setText(""); // Add Description
        startedDateTxtFld.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void finishBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishBtnActionPerformed
        viewWhatPane.setVisible(false);
        ConformationForm.sclName = schoolTxtFld.getText();
        ConformationForm.address = addressTxtFld.getText();
        ConformationForm.tp = tpTxtFld.getText();
        ConformationForm.description = descriptionTxtFld.getText(); // Add Description
        ConformationForm.startedDate = startedDateTxtFld.getText();  //date
        ConformationForm.registedDate = date;    // date

        ConformationForm.sc = "School";
        new ConformationForm().setVisible(true);
    }//GEN-LAST:event_finishBtnActionPerformed

    private void descriptionTxtFldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descriptionTxtFldMouseClicked
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_descriptionTxtFldMouseClicked

    private void schoolIdCmb1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_schoolIdCmb1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_schoolIdCmb1ItemStateChanged

    private void schoolIdCmb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolIdCmb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schoolIdCmb1ActionPerformed

    private void setDate(){
        Date dt = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        date = sdf.format(dt);
    }
    
    public String date;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLbl;
    public javax.swing.JTextField addressTxtFld;
    private javax.swing.JLabel descriptionLbl;
    private javax.swing.JTextArea descriptionTxtFld;
    private javax.swing.JButton finishBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JComboBox<String> schoolIdCmb1;
    private javax.swing.JLabel schoolIdLbl3;
    private javax.swing.JLabel schoolNameLbl;
    public javax.swing.JTextField schoolTxtFld;
    private javax.swing.JLabel startedDateLbl;
    public javax.swing.JTextField startedDateTxtFld;
    private javax.swing.JLabel tpLbl;
    public javax.swing.JTextField tpTxtFld;
    // End of variables declaration//GEN-END:variables
}
