/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.scouthq.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author Reshan Pubudu
 */
public class ScoutHqDashBoard extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public ScoutHqDashBoard() {
        initComponents();
        this.setExtendedState(ScoutHqDashBoard.MAXIMIZED_BOTH);
        setDate();
        setTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewPane = new javax.swing.JPanel();
        dateLbl = new javax.swing.JLabel();
        RegistrationBtn = new javax.swing.JButton();
        timeLbl = new javax.swing.JLabel();
        updateDetails = new javax.swing.JButton();
        viewDetailsBtn = new javax.swing.JButton();
        meritBadgeBtn = new javax.swing.JButton();
        coreBadgeBtn = new javax.swing.JButton();
        newPassed = new javax.swing.JButton();
        picLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        viewPane.setBackground(new java.awt.Color(255, 255, 255));

        dateLbl.setFont(new java.awt.Font("DFKai-SB", 0, 36)); // NOI18N
        dateLbl.setForeground(new java.awt.Color(255, 255, 255));
        dateLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        RegistrationBtn.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        RegistrationBtn.setText("Registration");
        RegistrationBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegistrationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrationBtnActionPerformed(evt);
            }
        });

        timeLbl.setBackground(new java.awt.Color(255, 255, 255));
        timeLbl.setFont(new java.awt.Font("DFKai-SB", 0, 36)); // NOI18N
        timeLbl.setForeground(new java.awt.Color(255, 255, 255));
        timeLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        updateDetails.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        updateDetails.setText("Update Details");
        updateDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDetailsActionPerformed(evt);
            }
        });

        viewDetailsBtn.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        viewDetailsBtn.setText("View Details");
        viewDetailsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsBtnActionPerformed(evt);
            }
        });

        meritBadgeBtn.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        meritBadgeBtn.setText("Merit Badges");
        meritBadgeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        meritBadgeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meritBadgeBtnActionPerformed(evt);
            }
        });

        coreBadgeBtn.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        coreBadgeBtn.setText("Core Badges");
        coreBadgeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        coreBadgeBtn.setOpaque(false);
        coreBadgeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coreBadgeBtnActionPerformed(evt);
            }
        });

        newPassed.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        newPassed.setText("Newly Passed");
        newPassed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newPassed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPassedActionPerformed(evt);
            }
        });

        picLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/scouthq/image/dashBoard1.jpg"))); // NOI18N
        picLbl.setOpaque(true);

        javax.swing.GroupLayout viewPaneLayout = new javax.swing.GroupLayout(viewPane);
        viewPane.setLayout(viewPaneLayout);
        viewPaneLayout.setHorizontalGroup(
            viewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPaneLayout.createSequentialGroup()
                .addGap(830, 830, 830)
                .addComponent(newPassed, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(dateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(viewPaneLayout.createSequentialGroup()
                .addGap(830, 830, 830)
                .addComponent(coreBadgeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(viewPaneLayout.createSequentialGroup()
                .addGap(830, 830, 830)
                .addComponent(updateDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(viewPaneLayout.createSequentialGroup()
                .addGap(1107, 1107, 1107)
                .addComponent(timeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(viewPaneLayout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(RegistrationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(viewPaneLayout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(viewDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(viewPaneLayout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(meritBadgeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(picLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        viewPaneLayout.setVerticalGroup(
            viewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPaneLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(viewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewPaneLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(newPassed, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(200, 200, 200)
                .addComponent(coreBadgeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(viewPaneLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(updateDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(viewPaneLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(timeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(viewPaneLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(RegistrationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(viewPaneLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(viewDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(viewPaneLayout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addComponent(meritBadgeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(picLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 575, Short.MAX_VALUE)
        );

        //coreBadgeBtn.setBackground(new Color(240, 240, 240, 200));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Sitka Small", 1, 34)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SCOUT HEAD QUARTS - GALLE BRANCH");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Scout Head Quarts, Fort, Galle.      091-2227606");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/scouthq/image/WorldScoutLogo.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/scouthq/image/SriLankaScoutLogo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(viewPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(viewPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrationBtnActionPerformed
        DiningArea reg  = new DiningArea();
        reg.loadRegistration();
        reg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegistrationBtnActionPerformed

    private void coreBadgeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coreBadgeBtnActionPerformed
        DiningArea reg  = new DiningArea();
        reg.loadCoreBadge();
        reg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_coreBadgeBtnActionPerformed

    private void newPassedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPassedActionPerformed
        DiningArea reg  = new DiningArea();
        reg.loadNewlyPassedPane();
        reg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_newPassedActionPerformed

    private void viewDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsBtnActionPerformed
        DiningArea reg  = new DiningArea();
        DiningArea.viewWhatPane.setVisible(true);
        reg.loadViewDetails("Members");
        reg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewDetailsBtnActionPerformed

    private void meritBadgeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meritBadgeBtnActionPerformed
        DiningArea reg  = new DiningArea();
        reg.loadMeritBadge();
        reg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_meritBadgeBtnActionPerformed

    private void updateDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDetailsActionPerformed
        DiningArea reg  = new DiningArea();
        reg.loadUpdateDetails();
        reg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_updateDetailsActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void setDate(){
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd:MM:yyyy");
        dateLbl.setText(sdf.format(d));
    }
    
    private void setTime(){
        new Timer(0, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
                Date dt = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
                timeLbl.setText(sdf.format(dt));
            }

        } ).start();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            /*for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }*/
            UIManager.setLookAndFeel(new com.jtattoo.plaf.aluminium.AluminiumLookAndFeel());
        /*} catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoutHqDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoutHqDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoutHqDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);*/
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoutHqDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ScoutHqDashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegistrationBtn;
    private javax.swing.JButton coreBadgeBtn;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton meritBadgeBtn;
    private javax.swing.JButton newPassed;
    private javax.swing.JLabel picLbl;
    private javax.swing.JLabel timeLbl;
    private javax.swing.JButton updateDetails;
    private javax.swing.JButton viewDetailsBtn;
    public javax.swing.JPanel viewPane;
    // End of variables declaration//GEN-END:variables
}
