/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.scouthq.view;

import edu.ijse.scouthq.controller.ControllerFactory;
import edu.ijse.scouthq.controller.custom.SchoolController;
import edu.ijse.scouthq.dto.SchoolDTO;
import edu.ijse.scouthq.dto.TeacherDTO;
import edu.ijse.scouthq.dto.TeacherSchoolDTO;
import static edu.ijse.scouthq.view.DiningArea.viewWhatPane;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.ldap.ControlFactory;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Reshan Pubudu
 */
public class TeacherRegistrationPane extends javax.swing.JPanel {

    SchoolController ctrlSchool;
    
    /**
     * Creates new form TeacherRegistrationPane
     */
    public TeacherRegistrationPane() {
        initComponents();
        setDate();
        ctrlSchool = (SchoolController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.SCHOOL);
        setSchoolId();
        setDate();
        setBirthYear();
        setDay((String) birthMonthCmb.getSelectedItem(),Integer.parseInt((String) birthYearCmb.getSelectedItem()),birthDayCmb);
        setDay((String) joinMonthCmb.getSelectedItem(),Integer.parseInt((String) joinYearCmb.getSelectedItem()),joinDayCmb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fullNameLbl = new javax.swing.JLabel();
        joiningLbl = new javax.swing.JLabel();
        addressLbl = new javax.swing.JLabel();
        dateOfBirthLbl = new javax.swing.JLabel();
        nameInitTxtFld = new javax.swing.JTextField();
        nameFullTxtFld = new javax.swing.JTextField();
        addressTxtFld = new javax.swing.JTextField();
        tpLbl = new javax.swing.JLabel();
        tpTxtFld = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        finishBtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        nameInitLbl = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        schoolIdCmb = new javax.swing.JComboBox<>();
        schoolIdLbl2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        teacherTbl = new javax.swing.JTable();
        birthYearCmb = new javax.swing.JComboBox<>();
        birthMonthCmb = new javax.swing.JComboBox<>();
        birthDayCmb = new javax.swing.JComboBox<>();
        joinYearCmb = new javax.swing.JComboBox<>();
        joinMonthCmb = new javax.swing.JComboBox<>();
        joinDayCmb = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);

        fullNameLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fullNameLbl.setText("Fulll Name               ");

        joiningLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        joiningLbl.setText("Date Of Joining    ");

        addressLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addressLbl.setText("Address               ");

        dateOfBirthLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dateOfBirthLbl.setText("Date of Birth            ");

        nameInitTxtFld.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        nameInitTxtFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        nameInitTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameInitTxtFldActionPerformed(evt);
            }
        });

        nameFullTxtFld.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        nameFullTxtFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        nameFullTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFullTxtFldActionPerformed(evt);
            }
        });

        addressTxtFld.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        addressTxtFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        addressTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTxtFldActionPerformed(evt);
            }
        });

        tpLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tpLbl.setText("Telephon           ");

        tpTxtFld.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tpTxtFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        tpTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpTxtFldActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        finishBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        finishBtn.setText("Finish");
        finishBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishBtnActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText(":");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText(":");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText(":");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText(":");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText(":");

        nameInitLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameInitLbl.setText("Name (with initialize) ");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText(":");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        schoolIdCmb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        schoolIdCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolIdCmbActionPerformed(evt);
            }
        });

        schoolIdLbl2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        schoolIdLbl2.setText("School Of Working");

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jScrollPane4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane4MouseClicked(evt);
            }
        });

        teacherTbl.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        teacherTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", ""
            }
        ));
        teacherTbl.setToolTipText("If you want to remove working School, then select row..");
        teacherTbl.setCellSelectionEnabled(true);
        teacherTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacherTblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                teacherTblMouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(teacherTbl);
        teacherTbl.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (teacherTbl.getColumnModel().getColumnCount() > 0) {
            teacherTbl.getColumnModel().getColumn(0).setPreferredWidth(100);
            teacherTbl.getColumnModel().getColumn(1).setPreferredWidth(450);
        }

        birthYearCmb.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        birthYearCmb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        birthYearCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                birthYearCmbItemStateChanged(evt);
            }
        });

        birthMonthCmb.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        birthMonthCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "Juny", "July", "August", "September", "October", "November", "December" }));
        birthMonthCmb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        birthMonthCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                birthMonthCmbItemStateChanged(evt);
            }
        });
        birthMonthCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthMonthCmbActionPerformed(evt);
            }
        });

        birthDayCmb.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        birthDayCmb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        birthDayCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                birthDayCmbItemStateChanged(evt);
            }
        });

        joinYearCmb.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        joinYearCmb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        joinYearCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                joinYearCmbItemStateChanged(evt);
            }
        });

        joinMonthCmb.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        joinMonthCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "Juny", "July", "August", "September", "October", "November", "December" }));
        joinMonthCmb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        joinMonthCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                joinMonthCmbItemStateChanged(evt);
            }
        });
        joinMonthCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinMonthCmbActionPerformed(evt);
            }
        });

        joinDayCmb.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        joinDayCmb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        joinDayCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                joinDayCmbItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameInitLbl)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(nameInitTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fullNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(nameFullTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(schoolIdLbl2)
                                .addGap(14, 14, 14)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(schoolIdCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(addressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dateOfBirthLbl)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(birthYearCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(birthMonthCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(birthDayCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(addressTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tpLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(joiningLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(joinYearCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(joinMonthCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(joinDayCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tpTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(92, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(finishBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameInitLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(nameInitTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fullNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(nameFullTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateOfBirthLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(birthYearCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(birthMonthCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(birthDayCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(addressTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tpLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(tpTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(joiningLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(joinYearCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(joinMonthCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(joinDayCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(schoolIdLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(schoolIdCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finishBtn)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane4.getViewport().setBackground(Color.WHITE);
    }// </editor-fold>//GEN-END:initComponents

    private void nameInitTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameInitTxtFldActionPerformed
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_nameInitTxtFldActionPerformed

    private void nameFullTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFullTxtFldActionPerformed
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_nameFullTxtFldActionPerformed

    private void addressTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTxtFldActionPerformed
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_addressTxtFldActionPerformed

    private void tpTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpTxtFldActionPerformed
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_tpTxtFldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        viewWhatPane.setVisible(false);
        nameInitTxtFld.setText("");
        nameFullTxtFld.setText("");
        //dateOfBirthTxtFld.setText("");  
        addressTxtFld.setText("");
        tpTxtFld.setText("");
        //joiningDateTxtFld.setText("");
        //teacherTbl.
    }//GEN-LAST:event_jButton1ActionPerformed

    private void finishBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishBtnActionPerformed
        int i = 0;
        
        String nameInit = nameInitTxtFld.getText().trim();
        String nameFull = nameFullTxtFld.getText().trim();
        
        //String dateOfBirth = sdf.format(dateOfBirthCmb.getDate());// JXDatePicker set Date Format
        String dateOfBirthMonth = getMonthNo((String) birthMonthCmb.getSelectedItem());
        String dateOfBirth = birthYearCmb.getSelectedItem()+"-"+dateOfBirthMonth+"-"+birthDayCmb.getSelectedItem();
        String address = addressTxtFld.getText().trim();
        String tp  = tpTxtFld.getText().trim();
        String joinMonth = getMonthNo((String) joinMonthCmb.getSelectedItem());
        String joiningDate = joinYearCmb.getSelectedItem()+"-"+joinMonth+"-"+joinDayCmb.getSelectedItem();
        
        if(nameFull.matches("([A-Za-z]([\\s]*)?)*")){
            i++;
        }
        else{
            JOptionPane.showMessageDialog(this,"Sorry, Pleace enter a valid Name");
        }
        
        if(nameInit.equals("")){
            nameInit = nameFull;
        }
        
        if(!address.equals(null)){
            i++;
        }
        
        if(tp.matches("[0]\\d{9}")){
            i++;
        }
        else{
            JOptionPane.showMessageDialog(this,"Sorry, Pleace enter a valid Telephon Number");
        }
        
        ArrayList <String> sclIds = new ArrayList<>();
        DefaultTableModel dtm = (DefaultTableModel)teacherTbl.getModel();
        for(int j = 0; j< dtm.getRowCount(); j++){
            String sclId = (String) dtm.getValueAt(j, 0);
            sclIds.add(sclId);
        }
        
        if(i==3){ 
            ConformationForm.sclIds = sclIds;
            ConformationForm.nameInit = nameInit;
            ConformationForm.nameFull = nameFull;
            ConformationForm.dateOfBirth = dateOfBirth;
            ConformationForm.address = address;
            ConformationForm.tp = tp;
            ConformationForm.joiningDate = joiningDate;
            ConformationForm.registedDate = date;    // date

            ConformationForm.sc = "Teacher";
            new ConformationForm().setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this,"Sorry, Pleace Check and Re-enter a Valied Details");
        }
    }//GEN-LAST:event_finishBtnActionPerformed

    private void teacherTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherTblMouseClicked
        viewWhatPane.setVisible(false);
        DefaultTableModel dtm = (DefaultTableModel)teacherTbl.getModel();
        int index = teacherTbl.getSelectedRow();
        dtm.removeRow(index);
        System.out.println(teacherTbl.getColumnCount());
    }//GEN-LAST:event_teacherTblMouseClicked

    private void teacherTblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherTblMouseEntered
        teacherTbl.setToolTipText("If you want to remove working School, then select row..");
    }//GEN-LAST:event_teacherTblMouseEntered

    private void schoolIdCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolIdCmbActionPerformed
        try {
            String sclId = (String) schoolIdCmb.getSelectedItem();
            SchoolDTO schoolDTO = ctrlSchool.search(sclId);
            DefaultTableModel dtm = (DefaultTableModel)teacherTbl.getModel();
            int j = 0;
            for(int i = 0; i< dtm.getRowCount(); i++){
                if(sclId.equals(dtm.getValueAt(i, 0))){
                    j++;
                }
            }
            if(j==0){
                Object []tData = {sclId, schoolDTO.getName()};
                dtm.addRow(tData);
            }
        } catch (Exception ex) {
            Logger.getLogger(AddMeritBadge.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_schoolIdCmbActionPerformed

    private void jScrollPane4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane4MouseClicked
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_jScrollPane4MouseClicked

    private void birthYearCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_birthYearCmbItemStateChanged
        int yer = Integer.parseInt((String) birthYearCmb.getSelectedItem());
        setDay((String) birthMonthCmb.getSelectedItem(),yer,birthDayCmb);
        setJoinYear();
    }//GEN-LAST:event_birthYearCmbItemStateChanged

    private void birthMonthCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_birthMonthCmbItemStateChanged
        setDay((String) birthMonthCmb.getSelectedItem(),Integer.parseInt((String) birthYearCmb.getSelectedItem()),birthDayCmb);
    }//GEN-LAST:event_birthMonthCmbItemStateChanged

    private void birthMonthCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthMonthCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthMonthCmbActionPerformed

    private void birthDayCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_birthDayCmbItemStateChanged

    }//GEN-LAST:event_birthDayCmbItemStateChanged

    private void joinYearCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_joinYearCmbItemStateChanged
        //set ???????????????????????????????????????????????????????
        //int yer = Integer.parseInt((String) joinYearCmb.getSelectedItem());
        //setDay((String) joinMonthCmb.getSelectedItem(),Integer.parseInt((String) joinYearCmb.getSelectedItem()),joinDayCmb);
    }//GEN-LAST:event_joinYearCmbItemStateChanged

    private void joinMonthCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_joinMonthCmbItemStateChanged
        setDay((String) joinMonthCmb.getSelectedItem(),Integer.parseInt((String) joinYearCmb.getSelectedItem()),joinDayCmb);
    }//GEN-LAST:event_joinMonthCmbItemStateChanged

    private void joinMonthCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinMonthCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_joinMonthCmbActionPerformed

    private void joinDayCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_joinDayCmbItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_joinDayCmbItemStateChanged

    private void setSchoolId(){
        try {
            ArrayList<SchoolDTO> schoolDTO = ctrlSchool.getAll();
            for(SchoolDTO schoolDto : schoolDTO){
                schoolIdCmb.addItem(schoolDto.getSclId());
            }
        } catch (Exception ex) {
            Logger.getLogger(AddMeritBadge.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setDate(){
        Date dt = new Date();
        SimpleDateFormat sdfDate = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat sdfYear = new SimpleDateFormat("yyyy");
        SimpleDateFormat sdfMonth = new SimpleDateFormat("MM");
        SimpleDateFormat sdfDay = new SimpleDateFormat("dd");
        date = sdfDate.format(dt);
        year = sdfYear.format(dt);
        month = sdfMonth.format(dt);
        day = sdfDay.format(dt);
    }
    
    private void setBirthYear(){
        int yer = Integer.parseInt(year);
        yer-=10;
        for(;yer>=1914;yer--){
            birthYearCmb.addItem(""+yer);
        }
        setJoinYear();
    }
    
    private void setJoinYear(){
        int nowYer = Integer.parseInt(year);
        int birthYer = Integer.parseInt((String) birthYearCmb.getSelectedItem());
        int joinYer = birthYer+10;
        joinYearCmb.removeAllItems();
        for(;joinYer<=birthYer+19;joinYer++){
            if(joinYer<=nowYer){
                joinYearCmb.addItem(""+joinYer);
            }
            else break;
        }
        
        setDay((String) joinMonthCmb.getSelectedItem(),Integer.parseInt((String) joinYearCmb.getSelectedItem()),joinDayCmb);
    }
    
    private void setDay(String mnth,int yer,JComboBox cmb){
        int i = 0;
        switch (mnth){
            case "January" :
            case "March" :
            case "May" :
            case "July" :
            case "August" :
            case "October" :
            case "December" : i = 31;
            break;
            case "February" : i = 28;
            break;
            case "April" :
            case "Juny" :
            case "September" :
            case "November" : i = 30;
            break;
        }
        if(yer%4==0&& mnth.equals("February")){
            i = 29;
        }
        cmb.removeAllItems();
        if(i!=0){
            for(int k = i; k>=1; k--){
                cmb.addItem(""+k);
            }
        }
    }
    
    private String getMonthNo(String month){
        switch (month){
            case "January" : month = "1";
            break;
            case "February" : month = "2";
            break;
            case "March" : month = "3";
            break;
            case "April" : month = "4";
            break;
            case "May" : month = "5";
            break;
            case "Juny" : month = "6";
            break;
            case "July" : month = "7";
            break;
            case "August" : month = "8";
            break;
            case "September" : month = "9";
            break;
            case "October" : month = "10";
            break;
            case "November" : month = "11";
            break;
            case "December" : month = "12";
            break;
        }
        return month;
    }
    
    private String date;
    private String year;
    private String month;
    private String day;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLbl;
    public javax.swing.JTextField addressTxtFld;
    private javax.swing.JComboBox<String> birthDayCmb;
    private javax.swing.JComboBox<String> birthMonthCmb;
    private javax.swing.JComboBox<String> birthYearCmb;
    private javax.swing.JLabel dateOfBirthLbl;
    private javax.swing.JButton finishBtn;
    private javax.swing.JLabel fullNameLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<String> joinDayCmb;
    private javax.swing.JComboBox<String> joinMonthCmb;
    private javax.swing.JComboBox<String> joinYearCmb;
    private javax.swing.JLabel joiningLbl;
    public javax.swing.JTextField nameFullTxtFld;
    private javax.swing.JLabel nameInitLbl;
    public javax.swing.JTextField nameInitTxtFld;
    public javax.swing.JComboBox<String> schoolIdCmb;
    private javax.swing.JLabel schoolIdLbl2;
    private javax.swing.JTable teacherTbl;
    private javax.swing.JLabel tpLbl;
    public javax.swing.JTextField tpTxtFld;
    // End of variables declaration//GEN-END:variables
}
