/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.scouthq.view;

import edu.ijse.scouthq.controller.ControllerFactory;
import edu.ijse.scouthq.controller.custom.SchoolController;
import edu.ijse.scouthq.dto.SchoolDTO;
import static edu.ijse.scouthq.view.DiningArea.viewWhatPane;
import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Reshan Pubudu
 */
public class TeacherUpdatePane extends javax.swing.JPanel {

    SchoolController ctrlSchool;
    
    /**
     * Creates new form TeacherUpdatePane
     */
    public TeacherUpdatePane() {
        initComponents();
        ctrlSchool = (SchoolController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.SCHOOL);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fullNameLbl = new javax.swing.JLabel();
        joiningLbl = new javax.swing.JLabel();
        addressLbl = new javax.swing.JLabel();
        dateOfBirthLbl = new javax.swing.JLabel();
        nameInitTxtFld = new javax.swing.JTextField();
        dateOfBirthTxtFld = new javax.swing.JTextField();
        nameFullTxtFld = new javax.swing.JTextField();
        addressTxtFld = new javax.swing.JTextField();
        tpLbl = new javax.swing.JLabel();
        tpTxtFld = new javax.swing.JTextField();
        joiningDateTxtFld = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        finishBtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        nameInitLbl = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        schoolIdCmb = new javax.swing.JComboBox<>();
        schoolIdLbl2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        schoolIdLbl3 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        schoolIdCmb1 = new javax.swing.JComboBox<>();

        setOpaque(false);

        jPanel1.setOpaque(false);

        fullNameLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fullNameLbl.setText("Fulll Name               ");

        joiningLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        joiningLbl.setText("Date Of Joining    ");

        addressLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addressLbl.setText("Address               ");

        dateOfBirthLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dateOfBirthLbl.setText("Date of Birth            ");

        nameInitTxtFld.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        nameInitTxtFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        nameInitTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameInitTxtFldActionPerformed(evt);
            }
        });

        dateOfBirthTxtFld.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        dateOfBirthTxtFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        dateOfBirthTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateOfBirthTxtFldActionPerformed(evt);
            }
        });

        nameFullTxtFld.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        nameFullTxtFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        nameFullTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFullTxtFldActionPerformed(evt);
            }
        });

        addressTxtFld.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        addressTxtFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        addressTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTxtFldActionPerformed(evt);
            }
        });

        tpLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tpLbl.setText("Telephon           ");

        tpTxtFld.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tpTxtFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        tpTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpTxtFldActionPerformed(evt);
            }
        });

        joiningDateTxtFld.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        joiningDateTxtFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        joiningDateTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joiningDateTxtFldActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        finishBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        finishBtn.setText("Finish");
        finishBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishBtnActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText(":");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText(":");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText(":");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText(":");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText(":");

        nameInitLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameInitLbl.setText("Name (with initialize) ");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText(":");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        schoolIdCmb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        schoolIdCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolIdCmbActionPerformed(evt);
            }
        });

        schoolIdLbl2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        schoolIdLbl2.setText("School Of Working");

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jScrollPane4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane4MouseClicked(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", ""
            }
        ));
        jTable1.setToolTipText("If you want to remove working School, then select row..");
        jTable1.setColumnSelectionAllowed(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable1MouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(jTable1);

        schoolIdLbl3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        schoolIdLbl3.setText("Teacher Id");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText(":");

        schoolIdCmb1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        schoolIdCmb1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        schoolIdCmb1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                schoolIdCmb1ItemStateChanged(evt);
            }
        });
        schoolIdCmb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolIdCmb1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(schoolIdLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(schoolIdCmb1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nameInitLbl)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(nameInitTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fullNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(nameFullTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dateOfBirthLbl)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(dateOfBirthTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(addressTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tpLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(tpTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(joiningLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(joiningDateTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(schoolIdLbl2)
                                .addGap(14, 14, 14)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(schoolIdCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(175, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(finishBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(schoolIdCmb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(schoolIdLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameInitLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(nameInitTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fullNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(nameFullTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateOfBirthLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(dateOfBirthTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(addressTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tpLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(tpTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(joiningLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(joiningDateTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(schoolIdLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(schoolIdCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finishBtn)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane4.getViewport().setBackground(Color.WHITE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameInitTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameInitTxtFldActionPerformed
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_nameInitTxtFldActionPerformed

    private void dateOfBirthTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateOfBirthTxtFldActionPerformed
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_dateOfBirthTxtFldActionPerformed

    private void nameFullTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFullTxtFldActionPerformed
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_nameFullTxtFldActionPerformed

    private void addressTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTxtFldActionPerformed
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_addressTxtFldActionPerformed

    private void tpTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpTxtFldActionPerformed
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_tpTxtFldActionPerformed

    private void joiningDateTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joiningDateTxtFldActionPerformed
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_joiningDateTxtFldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        viewWhatPane.setVisible(false);
        nameInitTxtFld.setText("");
        nameFullTxtFld.setText("");
        dateOfBirthTxtFld.setText("");
        addressTxtFld.setText("");
        tpTxtFld.setText("");
        joiningDateTxtFld.setText("");
        //jTable1.setRow
    }//GEN-LAST:event_jButton1ActionPerformed

    private void finishBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishBtnActionPerformed
        viewWhatPane.setVisible(false);
        /*String nameInit = nameInitTxtFld.getText();
        String nameFull = nameFullTxtFld.getText();
        String dateOfBirth = dateOfBirthTxtFld.getText();
        String address = addressTxtFld.getText();
        int tp = Integer.parseInt(tpTxtFld.getText());
        String joiningDate =joiningDateTxtFld.getText();

        ArrayList <String> sclIds = new ArrayList<>();
        DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
        for(int i = 0; i< dtm.getRowCount(); i++){
            String sclId = (String) dtm.getValueAt(i, 0);
            sclIds.add(sclId);
        }

        ConformationForm.sclIds = sclIds;
        ConformationForm.nameInit = nameInit;
        ConformationForm.nameFull = nameFull;
        ConformationForm.dateOfBirth = dateOfBirth;  //date
        ConformationForm.address = address;
        ConformationForm.tp = tp;
        ConformationForm.joiningDate = joiningDate;  //date
        ConformationForm.registedDate = date;    // date

        ConformationForm.sc = "Teacher";
        new ConformationForm().setVisible(true);*/
    }//GEN-LAST:event_finishBtnActionPerformed

    private void schoolIdCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolIdCmbActionPerformed
        try {
            String sclId = (String) schoolIdCmb.getSelectedItem();
            SchoolDTO schoolDTO = ctrlSchool.search(sclId);
            DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
            int j = 0;
            for(int i = 0; i< dtm.getRowCount(); i++){
                if(sclId.equals(dtm.getValueAt(i, 0))){
                    j++;
                }
            }
            if(j==0){
                Object []tData = {sclId, schoolDTO.getName()};
                dtm.addRow(tData);
            }
        } catch (Exception ex) {
            Logger.getLogger(AddMeritBadge.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_schoolIdCmbActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        viewWhatPane.setVisible(false);
        DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
        int index = jTable1.getSelectedRow();
        dtm.removeRow(index);
        System.out.println(jTable1.getColumnCount());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseEntered
        jTable1.setToolTipText("If you want to remove working School, then select row..");
    }//GEN-LAST:event_jTable1MouseEntered

    private void jScrollPane4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane4MouseClicked
        viewWhatPane.setVisible(false);
    }//GEN-LAST:event_jScrollPane4MouseClicked

    private void schoolIdCmb1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_schoolIdCmb1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_schoolIdCmb1ItemStateChanged

    private void schoolIdCmb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolIdCmb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schoolIdCmb1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLbl;
    public javax.swing.JTextField addressTxtFld;
    private javax.swing.JLabel dateOfBirthLbl;
    public javax.swing.JTextField dateOfBirthTxtFld;
    private javax.swing.JButton finishBtn;
    private javax.swing.JLabel fullNameLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    public javax.swing.JTextField joiningDateTxtFld;
    private javax.swing.JLabel joiningLbl;
    public javax.swing.JTextField nameFullTxtFld;
    private javax.swing.JLabel nameInitLbl;
    public javax.swing.JTextField nameInitTxtFld;
    public javax.swing.JComboBox<String> schoolIdCmb;
    public javax.swing.JComboBox<String> schoolIdCmb1;
    private javax.swing.JLabel schoolIdLbl2;
    private javax.swing.JLabel schoolIdLbl3;
    private javax.swing.JLabel tpLbl;
    public javax.swing.JTextField tpTxtFld;
    // End of variables declaration//GEN-END:variables
}
