/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.scouthq.view;

import static edu.ijse.scouthq.view.Registration.headPane;
import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author Reshan Pubudu
 */
public class UpdateDetails extends javax.swing.JPanel {

    /**
     * Creates new form UpdateDetailse
     */
    public UpdateDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        headPane = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        scoutLbl = new javax.swing.JLabel();
        girlScoutLbl = new javax.swing.JLabel();
        roverLbl = new javax.swing.JLabel();
        teacherLbl = new javax.swing.JLabel();
        cubScoutLbl = new javax.swing.JLabel();
        schoollbl = new javax.swing.JLabel();
        regPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setOpaque(false);

        headPane.setBackground(new java.awt.Color(51, 51, 51));
        headPane.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        headPane.setForeground(new java.awt.Color(0, 0, 255));
        headPane.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51, 70));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(0, 0, 0)));

        scoutLbl.setBackground(new java.awt.Color(170, 204, 255));
        scoutLbl.setDisplayedMnemonic('b');
        scoutLbl.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        scoutLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoutLbl.setText("Boy Scout");
        scoutLbl.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        scoutLbl.setName("catagory"); // NOI18N
        scoutLbl.setOpaque(true);
        scoutLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scoutLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                scoutLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                scoutLblMouseExited(evt);
            }
        });

        girlScoutLbl.setBackground(new java.awt.Color(170, 204, 255));
        girlScoutLbl.setDisplayedMnemonic('g');
        girlScoutLbl.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        girlScoutLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        girlScoutLbl.setText(" Girl Scout");
        girlScoutLbl.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        girlScoutLbl.setName("catagory"); // NOI18N
        girlScoutLbl.setOpaque(true);
        girlScoutLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                girlScoutLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                girlScoutLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                girlScoutLblMouseExited(evt);
            }
        });

        roverLbl.setBackground(new java.awt.Color(170, 204, 255));
        roverLbl.setDisplayedMnemonic('r');
        roverLbl.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        roverLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roverLbl.setText("Rover");
        roverLbl.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        roverLbl.setName("catagory"); // NOI18N
        roverLbl.setOpaque(true);
        roverLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roverLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                roverLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                roverLblMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                roverLblMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                roverLblMouseReleased(evt);
            }
        });

        teacherLbl.setBackground(new java.awt.Color(170, 204, 255));
        teacherLbl.setDisplayedMnemonic('t');
        teacherLbl.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        teacherLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        teacherLbl.setText("Teacher");
        teacherLbl.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        teacherLbl.setName("catagory"); // NOI18N
        teacherLbl.setOpaque(true);
        teacherLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacherLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                teacherLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                teacherLblMouseExited(evt);
            }
        });

        cubScoutLbl.setBackground(new java.awt.Color(170, 204, 255));
        cubScoutLbl.setDisplayedMnemonic('c');
        cubScoutLbl.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        cubScoutLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cubScoutLbl.setText(" Cub Scout");
        cubScoutLbl.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        cubScoutLbl.setName("catagory"); // NOI18N
        cubScoutLbl.setOpaque(true);
        cubScoutLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cubScoutLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cubScoutLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cubScoutLblMouseExited(evt);
            }
        });

        schoollbl.setBackground(new java.awt.Color(170, 204, 255));
        schoollbl.setDisplayedMnemonic('s');
        schoollbl.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        schoollbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        schoollbl.setText("School");
        schoollbl.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        schoollbl.setName("catagory"); // NOI18N
        schoollbl.setOpaque(true);
        schoollbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                schoollblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                schoollblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                schoollblMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                schoollblMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                schoollblMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(cubScoutLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(scoutLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(girlScoutLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(roverLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(teacherLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(schoollbl, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cubScoutLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scoutLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(girlScoutLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roverLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(teacherLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(schoollbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        regPane.setBackground(new java.awt.Color(51, 153, 255));
        regPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        regPane.setOpaque(false);
        regPane.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1099, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(headPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(headPane, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regPane, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel4);
        jPanel4.setBounds(0, 0, 1119, 718);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/scouthq/image/winter-stripes-background11.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1120, 720);
    }// </editor-fold>//GEN-END:initComponents

    private void scoutLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scoutLblMouseClicked
        loadScoutUpdatePane();
    }//GEN-LAST:event_scoutLblMouseClicked

    private void scoutLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scoutLblMouseEntered
        mouseEnter(scoutLbl);
    }//GEN-LAST:event_scoutLblMouseEntered

    private void scoutLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scoutLblMouseExited
        mouseExit(scoutLbl);
    }//GEN-LAST:event_scoutLblMouseExited

    private void girlScoutLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_girlScoutLblMouseClicked
        regPane.removeAll();
        GirlUpdatePane grlUpdatePane = new GirlUpdatePane();
        grlUpdatePane.setSize(regPane.getSize());
        regPane.add(grlUpdatePane);
        headPane.setText("Girl Scout Update Details");
        regPane.updateUI();
    }//GEN-LAST:event_girlScoutLblMouseClicked

    private void girlScoutLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_girlScoutLblMouseEntered
        mouseEnter(girlScoutLbl);
    }//GEN-LAST:event_girlScoutLblMouseEntered

    private void girlScoutLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_girlScoutLblMouseExited
        mouseExit(girlScoutLbl);
    }//GEN-LAST:event_girlScoutLblMouseExited

    private void roverLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roverLblMouseClicked
        regPane.removeAll();
        RoverUpdatePane roverUpdatePane = new RoverUpdatePane();
        roverUpdatePane.setSize(regPane.getSize());
        regPane.add(roverUpdatePane);
        headPane.setText("Rover Scout Update Details");
        regPane.updateUI();
    }//GEN-LAST:event_roverLblMouseClicked

    private void roverLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roverLblMouseEntered
        mouseEnter(roverLbl);
    }//GEN-LAST:event_roverLblMouseEntered

    private void roverLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roverLblMouseExited
        mouseExit(roverLbl);
    }//GEN-LAST:event_roverLblMouseExited

    private void roverLblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roverLblMousePressed
        /*schoolIdLbl1.setVisible(false);
        jLabel16.setVisible(false);
        schoolIdCmb.setVisible(false);
        schoolNameLbl.setVisible(false);
        jLabel24.setVisible(false);
        schoolTxtFld.setVisible(false);*/
    }//GEN-LAST:event_roverLblMousePressed

    private void roverLblMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roverLblMouseReleased
        /*joiningLbl.setLocation(88, 353);
        jLabel15.setLocation(225, 353);
        joiningDateTxtFld.setLocation(275, 353);*/
    }//GEN-LAST:event_roverLblMouseReleased

    private void teacherLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherLblMouseClicked
        regPane.removeAll();
        TeacherUpdatePane teacherUpdatePane = new TeacherUpdatePane();
        teacherUpdatePane.setSize(regPane.getSize());
        regPane.add(teacherUpdatePane);
        headPane.setText("Teachers Update Details");
        regPane.updateUI();
        /*regPane.removeAll();
        TeacherRegistrationPane teacherRegPane = new TeacherRegistrationPane();
        teacherRegPane.setSize(regPane.getSize());
        teacherRegPane.setVisible(true);
        regPane.add(teacherRegPane);
        headPane.setText("Teachers Registration");
        regPane.repaint();
        regPane.revalidate();*/
    }//GEN-LAST:event_teacherLblMouseClicked

    private void teacherLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherLblMouseEntered
        mouseEnter(teacherLbl);
    }//GEN-LAST:event_teacherLblMouseEntered

    private void teacherLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherLblMouseExited
        mouseExit(teacherLbl);
    }//GEN-LAST:event_teacherLblMouseExited

    private void cubScoutLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cubScoutLblMouseClicked
        regPane.removeAll();
        CubUpdatePane cubUpdatePane = new CubUpdatePane();
        cubUpdatePane.setSize(regPane.getSize());
        regPane.removeAll();
        regPane.add(cubUpdatePane);
        headPane.setText("Cub Scout Update Details");
        regPane.updateUI();

    }//GEN-LAST:event_cubScoutLblMouseClicked

    private void cubScoutLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cubScoutLblMouseEntered
        mouseEnter(cubScoutLbl);
    }//GEN-LAST:event_cubScoutLblMouseEntered

    private void cubScoutLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cubScoutLblMouseExited
        mouseExit(cubScoutLbl);
    }//GEN-LAST:event_cubScoutLblMouseExited

    private void schoollblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schoollblMouseClicked
        regPane.removeAll();
        SchoolUpdatePane schoolUpdatePane = new SchoolUpdatePane();
        schoolUpdatePane.setSize(regPane.getSize());
        regPane.add(schoolUpdatePane);
        headPane.setText("School Update Details");
        regPane.updateUI();
    }//GEN-LAST:event_schoollblMouseClicked

    private void schoollblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schoollblMouseEntered
        mouseEnter(schoollbl);
    }//GEN-LAST:event_schoollblMouseEntered

    private void schoollblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schoollblMouseExited
        mouseExit(schoollbl);
    }//GEN-LAST:event_schoollblMouseExited

    private void schoollblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schoollblMousePressed
        /*nameInitLbl.setVisible(false);
        jLabel25.setVisible(false);
        nameInitTxtFld.setVisible(false);
        fullNameLbl.setVisible(false);
        jLabel20.setVisible(false);
        nameFullTxtFld.setVisible(false);
        dateOfBirthLbl.setVisible(false);
        jLabel19.setVisible(false);
        dateOfBirthTxtFld.setVisible(false);
        schoolIdLbl1.setVisible(false);
        jLabel16.setVisible(false);
        schoolIdCmb.setVisible(false);*/
    }//GEN-LAST:event_schoollblMousePressed

    private void schoollblMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schoollblMouseReleased

    }//GEN-LAST:event_schoollblMouseReleased
    
    public void loadScoutUpdatePane(){
        regPane.removeAll();
        BoyUpdatePane boyUpdatePane = new BoyUpdatePane();
        boyUpdatePane.setSize(regPane.getSize());
        regPane.removeAll();
        regPane.add(boyUpdatePane);
        headPane.setText("Boy Scout Update Details");
        regPane.updateUI();
    }
    
    private void mouseEnter(JLabel jLabel){
        jLabel.setBackground(new Color(0,114,222));
        jLabel.setForeground(Color.white);
    }
    
    private void mouseExit(JLabel jLabel){
        jLabel.setBackground(new Color(170,204,255));
        jLabel.setForeground(Color.black);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cubScoutLbl;
    private javax.swing.JLabel girlScoutLbl;
    public static javax.swing.JLabel headPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel regPane;
    private javax.swing.JLabel roverLbl;
    private javax.swing.JLabel schoollbl;
    private javax.swing.JLabel scoutLbl;
    private javax.swing.JLabel teacherLbl;
    // End of variables declaration//GEN-END:variables
}
